#!/usr/bin/env bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#
# Run AIDE check or, if no database found, init during startup
#

case $1 in

  start) 
    echo "Checking file integrity with aide..."
    if [ -f "/var/lib/aide/aide.db" ]; then
      start-stop-daemon -b -x /etc/config-tools/manage_integrity -S -- check 80
    else
      start-stop-daemon -b -x /etc/config-tools/manage_integrity -S -- init 80
    fi
    ;;

esac
