#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#
# automatic firmware restore after boot
#

case $1 in

	start)
		/etc/config-tools/auto_firmware_restore &
		;;

	*)
		echo "usage: auto_firmware_restore start"
		exit 1
		;;

esac
