#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#
# codesys_webserver
#

case $1 in

  start)
          if [ "`pidof webserver`" != "" ]; then
            echo "Codesys Webserver already started"
          else
            echo "Codesys Webserver starting"
            /etc/init.d/generate_password
            /usr/sbin/webserver >/dev/null 2>&1 &
            /etc/config-tools/codesys_webserver_watchdog &
          fi
          ;;

  stop)
          echo "Codesys Webserver stop"

          # get PID of watchdog by process list (pidof doesn't work here)
          grepOutput=`ps aux | grep codesys_webserver_watchdog`
          webserverPid=`echo $grepOutput | cut -d\  -f2`
          #echo "webserverPid:"$webserverPid

          # kill watchdog and webserver itself
          sudo /bin/kill -15 $webserverPid 2> /dev/null
          sudo /bin/kill -15 `pidof webserver` 2> /dev/null
          ;;

esac
