#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#
# drm
#
case $1 in

        start)
                echo "daemon-is-running=false" >"/etc/specific/features/feature_drm"
                mkdir -p /run/drm
                /usr/bin/drm /run/drm -s -o allow_other,gid=119
                ;;

esac
