#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

DONE=' ==> done.'
FAILED=' ==> failed!'
PASSFILE_DIR='/var/run/webserver'
PASSFILE="${PASSFILE_DIR}/password_webserver"

mkdir -p "${PASSFILE_DIR}" || exit 1

echo -n 'Generate new password...'
new_passwd="$(</dev/urandom tr -dc 'A-Za-z0-9!"'\''#%&()*+,-./:;<=>?@[]^_`{|}~' | dd bs=1 count=32 status=none)"
echo "${DONE}"

echo -n 'Update password of "visualisation" user...'
if echo -e "${new_passwd}\n${new_passwd}\n" | passwd 'visualisation' 1>/dev/null 2>&1; then
  echo "${DONE}"
else
  echo "${FAILED}"
  exit 1
fi

echo -n 'Create temporary password file for the webserver (overwrite if exists)...'
# Note: Only 'root' shall has access to the generated password file!
old_umask="$(umask)"
umask 177
echo "${new_passwd}" > "${PASSFILE}.tmp" && mv "${PASSFILE}.tmp" "${PASSFILE}"
umask "${old_umask}"
echo "$DONE"

