#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG

DONE="==> done."
FAILED="==> failed!"
PASSFILE="/tmp/password_webserver"

echo "Generate new password..."
NEWPASS=$(dd if=/dev/urandom count=40c 2>/dev/null | md5sum | cut -d ' ' -f 1)
echo $DONE
echo "Update password of "visualisation" user..."
/etc/config-tools/config_linux_user user=visualisation new-password=$NEWPASS confirm-password=$NEWPASS
if [ $(echo $?) == "0" ]
  then
    echo $DONE
  else
    echo $FAILED
    exit
fi

echo "Create temporary password file for the webserver (overwrite if exists)..."
rm -f $PASSFILE
#Note! Only 'root' shall access the generated password file.
UMASK_SAVED=$(umask)
umask o-rwx
echo $NEWPASS > $PASSFILE
umask $UMASK_SAVED
echo $DONE

