#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG

#
# ledserver
#

createXmlLink()
{
    local DEVCONF="$(/etc/config-tools/get_typelabel_value DEVCONF)"
    local ORDER="$(/etc/config-tools/get_typelabel_value ORDER)"

    if [ "$DEVCONF" == "" ]
    then
        DEVCONF="0x000F"
    fi

    if [ "${ORDER:4:2}" == "81" ]
    then
        PRODUCT="PFC100"
    elif [ "${ORDER:0:3}" == "762" ] || [ "${ORDER:0:5}" == "752-8" ]
    then
        PRODUCT="TP600"
    elif [ "${ORDER:0:6}" == "751-93" ]
    then
      PRODUCT="CC100"
    elif [ "${ORDER:0:3}" == "768" ]
    then
      PRODUCT="PFC200-ADV"
    elif [ "${ORDER:4:2}" == "82" ]
    then
        # default
        PRODUCT="PFC200"
      
        # full order number use 
        SUBORDER=$(echo "$ORDER" | awk -F/ '{print $2}')
        if [ -n "$SUBORDER" ]
        then
            # check that file with sub order number exists
            if [ -f "/etc/specific/led.${DEVCONF}.${PRODUCT}_${SUBORDER}.xml" ]
            then
                PRODUCT="${PRODUCT}_${SUBORDER}"
            fi
        fi
    else
        PRODUCT="default"
        DEVCONF="0x0000"
    fi
    echo "ledserverd: product = $PRODUCT"
    LED_XML="led.$DEVCONF.$PRODUCT.xml"
    ln -fs /etc/specific/$LED_XML /tmp/led.xml
}

setupEnvironment()
{
        # start errorsererd as daemon
        ORDER="$(/etc/config-tools/get_typelabel_value ORDER)"
        STRIPPED_ORDER=${ORDER//\//_}
        FAST_SETUP_FILE=/etc/specific/ledsetup-${STRIPPED_ORDER}
        
        #first check if we have a fast lookup-file
        if [ ! -e "$FAST_SETUP_FILE" ]
        then
          /etc/config-tools/config_ledserver_generate
        fi
        $FAST_SETUP_FILE
        
}

case $1 in

    start)
        createXmlLink
        setupEnvironment
        echo "Starting ledserverd"
        start-stop-daemon -S -x "/bin/ledserverd" -o -b
        echo "done."
        ;;


    stop)
        echo -n "Terminating ledserverd..."
        start-stop-daemon -K -n ledserverd
        echo "done"
        ;;

esac
