#!/bin/bash
#
# link devices
#

# this script link devices from sys-fs to /dev/. The devices that
# need to be linked are defined in /etc/specific/.devs_to_link.

DEVS_TO_LINK="/etc/specific/.devs_to_link"
DEV_SEARCH_PATH="/sys/devices/"

check_unnamed()
{
    local extract_result=$1
    local name="$2"
    local device="$3"

    if [[ $extract_result -ne 0 || -z "$name" ]]; then
        echo "unnamed_$device"
    else
        echo "$name"
    fi

    return 0
}

extract_nand_label()
{
    local ubi_device="$1"

    local name=""
    name="$(cat "/sys/class/ubi/$ubi_device/name")"
    check_unnamed $? "$name" "$ubi_device"

    return 0
}

extract_emmc_label()
{
    local partition_device="$1"

    local name=""
    name="$(blkid "/dev/$partition_device" | sed -n 's/.*LABEL=\"\(\S\+\)\".*/\1/p')"
    check_unnamed $? "$name" "$partition_device"

    return 0
}


if [[ -c "/dev/mtd8" ]]; then
    detach_ubi=false
    if [[ ! -e "/sys/class/ubi/ubi0_0" ]]; then
        /sbin/ubiattach --mtdn=8 &>/dev/null
        detach_ubi=true
    fi
    # static partitions for systems with internal flash nand
    PARTITION_NAND_ROOTFS1_DEV_NAME="ubi0_0"
    PARTITION_NAND_ROOTFS1_LINK_NAME="/dev/partition_$(extract_nand_label "$PARTITION_NAND_ROOTFS1_DEV_NAME")"
    PARTITION_NAND_ROOTFS2_DEV_NAME="ubi0_2"
    PARTITION_NAND_ROOTFS2_LINK_NAME="/dev/partition_$(extract_nand_label "$PARTITION_NAND_ROOTFS2_DEV_NAME")"
    PARTITION_NAND_HOME1_DEV_NAME="ubi0_1"
    PARTITION_NAND_HOME1_LINK_NAME="/dev/partition_$(extract_nand_label "$PARTITION_NAND_HOME1_DEV_NAME")"

    if $detach_ubi; then
        /sbin/ubidetach --mtdn=8 &>/dev/null
    fi
else
    # static partitions for systems with internal flash emmc
    ORDER="$(/etc/config-tools/get_typelabel_value ORDER)"
    if [ "${ORDER:0:5}" == "751-9" ]; then
      #CC100
      PARTITION_EMMC_BOOT_DEV_NAME="mmcblk1p2"
      PARTITION_EMMC_BOOT_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_BOOT_DEV_NAME")"
      PARTITION_EMMC_ROOTFS1_DEV_NAME="mmcblk1p5"
      PARTITION_EMMC_ROOTFS1_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_ROOTFS1_DEV_NAME")"
      PARTITION_EMMC_ROOTFS2_DEV_NAME="mmcblk1p8"
      PARTITION_EMMC_ROOTFS2_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_ROOTFS2_DEV_NAME")"
      PARTITION_EMMC_HOME1_DEV_NAME="mmcblk1p6"
      PARTITION_EMMC_HOME1_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_HOME1_DEV_NAME")"
      PARTITION_EMMC_HOME2_DEV_NAME="mmcblk1p7"
      PARTITION_EMMC_HOME2_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_HOME2_DEV_NAME")"
      PARTITION_EMMC_LOG_DEV_NAME="mmcblk1p3"
      PARTITION_EMMC_LOG_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_LOG_DEV_NAME")"
      PARTITION_EMMC_SETTINGS_DEV_NAME="mmcblk1p4"
      PARTITION_EMMC_SETTINGS_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_SETTINGS_DEV_NAME")"
    else
      #TP600
      PARTITION_EMMC_BOOT_DEV_NAME="mmcblk1p1"
      PARTITION_EMMC_BOOT_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_BOOT_DEV_NAME")"
      PARTITION_EMMC_ROOTFS1_DEV_NAME="mmcblk1p7"
      PARTITION_EMMC_ROOTFS1_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_ROOTFS1_DEV_NAME")"
      PARTITION_EMMC_ROOTFS2_DEV_NAME="mmcblk1p10"
      PARTITION_EMMC_ROOTFS2_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_ROOTFS2_DEV_NAME")"
      PARTITION_EMMC_HOME1_DEV_NAME="mmcblk1p8"
      PARTITION_EMMC_HOME1_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_HOME1_DEV_NAME")"
      PARTITION_EMMC_HOME2_DEV_NAME="mmcblk1p9"
      PARTITION_EMMC_HOME2_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_HOME2_DEV_NAME")"
      PARTITION_EMMC_LOG_DEV_NAME="mmcblk1p5"
      PARTITION_EMMC_LOG_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_LOG_DEV_NAME")"
      PARTITION_EMMC_SETTINGS_DEV_NAME="mmcblk1p6"
      PARTITION_EMMC_SETTINGS_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_SETTINGS_DEV_NAME")"
    fi
fi

# get configured kbus uart from sys-fs
if [ -e /dev/kbus0 ]; then
    KBUS_TTY_PFCXXX_DEV_NAME="$(cat /sys/class/wago/system/kbus_tty_device_name)"
    KBUS_TTY_PFCXXX_LINK_NAME="/dev/ttyKbus"
fi
# get configured rs232_485 uart from sys-fs
SERIAL_TTY_PFCXXX_DEV_NAME="$(cat /sys/class/wago/system/tty_rs232_485)"
SERIAL_TTY_PFCXXX_LINK_NAME="/dev/serial"

# get configured service uart from sys-fs
SERVICE_TTY_PFCXXX_DEV_NAME="$(cat /sys/class/wago/system/tty_service)"
SERVICE_TTY_PFCXXX_LINK_NAME="/dev/service"

# get configured modem uart from sys-fs
# the device does always exist in all PFCs and displays
GSM_MODEM_TTY_PFCXXX_DEV_NAME="ttyMdm0"
GSM_MODEM_TTY_PFCXXX_LINK_NAME="/dev/ttyRUNTIME66"

# CC100
TTY_CC100_RS485_DEV_NAME="ttySTM1"
TTY_CC100_RS485_LINK_NAME="/dev/ttyRUNTIME0"

# profibus dp uio device names
PROFIBUS_DP_UIO_XINT_NAME="UIO_DPC31_XINT"
PROFIBUS_DP_UIO_SYNC_NAME="UIO_DPC31_SYNC"

if [ ! -f "${DEVS_TO_LINK}" ]; then
        echo "${DEVS_TO_LINK} not found"
        exit 1
fi

# create list of device-paths
index=0
device_paths=()

while read line; do
        tmp_dev=$(find ${DEV_SEARCH_PATH} -iname ${line})
        if [ ! -z "${tmp_dev}" ]; then
                device_paths[$index]=${tmp_dev}
                index=$(($index + 1))
        else
                echo "${line} not found in ${DEV_SEARCH_PATH}"
        fi
done <${DEVS_TO_LINK}

if [ ${#device_paths[@]} -eq 0 ]; then
        echo "no device-paths found"
        exit 1
fi

case $1 in

  start)
        # if device kbus0 exist the kernel supports KBus so from the userspace we can check if kbus0 exists
        if [ -e /dev/kbus0 ]; then
                if [ -c "/dev/${KBUS_TTY_PFCXXX_DEV_NAME}" ]; then
                        ln -s /dev/${KBUS_TTY_PFCXXX_DEV_NAME} "${KBUS_TTY_PFCXXX_LINK_NAME}"
                else
                        echo "ERROR: could not set ${KBUS_TTY_PFCXXX_LINK_NAME}, kbus will not be active"
                fi
        fi

        if [ -c "/dev/${SERIAL_TTY_PFCXXX_DEV_NAME}" ]; then
                ln -s /dev/${SERIAL_TTY_PFCXXX_DEV_NAME} "${SERIAL_TTY_PFCXXX_LINK_NAME}"
                echo "hardware-available=true" >"/etc/specific/features/rs232_485-interface"
        else
                echo "INFO: tty_rs232_485 is not available"
                echo "hardware-available=false" >"/etc/specific/features/rs232_485-interface"
        fi

        if [ -c "/dev/${SERVICE_TTY_PFCXXX_DEV_NAME}" ]; then
                ln -s /dev/${SERVICE_TTY_PFCXXX_DEV_NAME} "${SERVICE_TTY_PFCXXX_LINK_NAME}"
                echo "hardware-available=true" >"/etc/specific/features/serial-service-interface"
        else
                echo "ERROR: could not set ${SERVICE_TTY_PFCXXX_LINK_NAME}, getty will fail"
                echo "hardware-available=false" >"/etc/specific/features/serial-service-interface"
        fi

        ln -s /dev/${GSM_MODEM_TTY_PFCXXX_DEV_NAME} "${GSM_MODEM_TTY_PFCXXX_LINK_NAME}"

        if $(lsuio | grep -q "$PROFIBUS_DP_UIO_XINT_NAME"); then
                if $(lsuio | grep -q "$PROFIBUS_DP_UIO_SYNC_NAME"); then
                        echo "hardware-available=true" >"/etc/specific/features/profibus-dp-slave"
                else
                        echo "INFO: PROFIBUS DP device \"$PROFIBUS_DP_UIO_SYNC_NAME\" not available"
                        echo "hardware-available=false" >"/etc/specific/features/profibus-dp-slave"
                fi
        else
                echo "INFO: PROFIBUS DP device \"$PROFIBUS_DP_UIO_XINT_NAME\" not available"
                echo "hardware-available=false" >"/etc/specific/features/profibus-dp-slave"
        fi

        for path in "${device_paths[@]}"; do
                ln -s ${path} /dev/
        done

        # ----- internal flash partitions -----
        if [[ -c "/dev/mtd8" ]]; then
                ln -s /dev/${PARTITION_NAND_ROOTFS1_DEV_NAME}    "${PARTITION_NAND_ROOTFS1_LINK_NAME}"
                ln -s /dev/${PARTITION_NAND_ROOTFS2_DEV_NAME}    "${PARTITION_NAND_ROOTFS2_LINK_NAME}"
                ln -s /dev/${PARTITION_NAND_HOME1_DEV_NAME}      "${PARTITION_NAND_HOME1_LINK_NAME}"
        else
                ln -s /dev/${PARTITION_EMMC_BOOT_DEV_NAME}       "${PARTITION_EMMC_BOOT_LINK_NAME}"
                ln -s /dev/${PARTITION_EMMC_ROOTFS1_DEV_NAME}    "${PARTITION_EMMC_ROOTFS1_LINK_NAME}"
                ln -s /dev/${PARTITION_EMMC_ROOTFS2_DEV_NAME}    "${PARTITION_EMMC_ROOTFS2_LINK_NAME}"
                ln -s /dev/${PARTITION_EMMC_HOME1_DEV_NAME}      "${PARTITION_EMMC_HOME1_LINK_NAME}"
                ln -s /dev/${PARTITION_EMMC_HOME2_DEV_NAME}      "${PARTITION_EMMC_HOME2_LINK_NAME}"
                ln -s /dev/${PARTITION_EMMC_LOG_DEV_NAME}        "${PARTITION_EMMC_LOG_LINK_NAME}"
                ln -s /dev/${PARTITION_EMMC_SETTINGS_DEV_NAME}   "${PARTITION_EMMC_SETTINGS_LINK_NAME}"
        fi

        # CC100 RS485
        if [ -c "/dev/${TTY_CC100_RS485_DEV_NAME}" ]; then
            ln -s /dev/${TTY_CC100_RS485_DEV_NAME} "${TTY_CC100_RS485_LINK_NAME}"
        fi

  ;;
  stop)
  ;;

esac
