#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2020-2022 WAGO GmbH & Co. KG

#
# logsystemstart
#

SYSTEM_START_DONE_FILE="/var/run/systemstart.done"

case $1 in

    start)
        /usr/bin/touch "$SYSTEM_START_DONE_FILE"
        eventmsg -n init 0x80000012
        echo "System start done."
        ;;

    stop)
        echo ""
        ;;

esac
