#!/bin/sh
#
# /etc/init.d/pure-ftpd
#

PATH=/bin:/usr/bin:/sbin:/usr/sbin

# defaults
DAEMON="pure-ftpd"
NAME="pure-ftpd"
PREFIX="pure-ftpd: "
DAEMON_OPTIONS="-C 10 -E -p 32000:32100 -b -H"
DAEMON_PIDFILE=/var/run/pure-ftpd.pid

HELPER="pure-uploadscript"
HELPER_START_SCRIPT=""
HELPER_OPTIONS="-B -u 0 -g 0"

# read config (will override defaults)
DEFAULTS="/etc/pure-ftpd.defaults"
if [ -r $DEFAULTS ]; then
	. $DEFAULTS
else
	echo "${PREFIX}no $DEFAULTS found."
fi

trap "" 1
trap "" 15

which $DAEMON || { echo "${PREFIX}$DAEMON not found"; exit; }


if [ ! -z $HELPER_START_SCRIPT ] ; then
	DAEMON_OPTIONS="$DAEMON_OPTIONS -o"
fi

if [[ -f /etc/pure-ftpd.conf ]]; then
	. /etc/pure-ftpd.conf

	if [[ "$TLS" != "" ]]; then
		DAEMON_OPTIONS="$DAEMON_OPTIONS -Y $TLS -J DEFAULT:!RC4:!3DES:!IDEA"
	fi

fi

start_helper(){
	if [ ! -z $HELPER_START_SCRIPT ]; then
		which $HELPER || { echo "${PREFIX}$HELPER not found"; exit; }
		echo "${PREFIX}starting upload helper daemon..."
		$HELPER $HELPER_OPTIONS -r $HELPER_START_SCRIPT
	else
		echo "${PREFIX}no upload script defined, skipping"
	fi
}

stop_helper(){
	killall -9 "$HELPER"
}

start_daemon(){
	# set timezone (used for file time responses),
	# this is redundant since build in timezone at compile time should be UTC also
	export TZ="UTC0"

	# start FTP daemon
	which $DAEMON
	daemonPath=`which $DAEMON`
	sudo $daemonPath -g $DAEMON_PIDFILE $DAEMON_OPTIONS &
}

stop_daemon(){
	if [ -e "$DAEMON_PIDFILE" ]; then
		PID=`cat $DAEMON_PIDFILE`

		# stop/killing open subprocesses
		ACTIVESUBS=$(ps -ef | awk '$3 == '$PID' { print $2 }' | wc -l)
		if [ $ACTIVESUBS -gt 0 ]; then
			kill `ps -ef| awk '$3 == '$PID' { print $2 }'`
			case $? in
				0)
				echo "${PREFIX}subprocesses stopped"
				;;
				*)
				kill -9 `ps -ef| awk '$3 == '$PID' { print $2 }'`
				echo "${PREFIX}subprocesses failed to stop - killed"
				;;
			esac
		fi

		# stop daemon (main process)
		kill $PID
		case $? in
			0)
			echo "${PREFIX}$NAME stopped"
			;;
			*)
			kill -9 $PID
			echo "${PREFIX}failed to stop $NAME - process killed"
			;;
		esac
		rm -f $DAEMON_PIDFILE
		echo "${PREFIX}pidfile removed"
	else
		echo "${PREFIX}pid file not found - process not running"
	fi
}

start(){
	start_daemon
	start_helper
}

stop(){
	stop_daemon
	stop_helper
}

case "$1" in
	start)
		echo "${PREFIX}starting $NAME..."
		start
		echo "done"
	;;

	stop)
		echo "${PREFIX}stopping $NAME..."
		stop
		echo "done"
	;;

	reload)
	echo -n "${PREFIX}reloading $NAME configuration..."
	if [ -e "$DAEMON_PIDFILE" ]; then
		kill -HUP `cat $DAEMON_PIDFILE`
		echo " done."
	else
		echo "pid file not found - process not running"
	fi
	;;

	force-reload|restart)
		echo -n "${PREFIX}restarting $NAME."
		stop
		echo -n "."
		sleep 2
		echo -n "."
		start
		echo " done."
	;;

	*)
	echo "Usage: /etc/init.d/$NAME {start|stop|reload|restart|force-reload|help}"
	exit 1
	;;
esac

exit 0
