#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#
# remountrw
#
case $1 in

	start)
		echo -n "remounting root rw..."
		mount / -o remount,rw >/dev/null 2>&1
		if [ "$?" -ne "0" ]; then
			echo "failed, aborting"
			exit 1
		fi
		echo "done"
esac

