#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG

#
# /etc/init.d/routing
#

case $1 in

	start)
		/etc/config-tools/events/networking/update_routing
		;;

	stop)
		;;

	restart)
		/etc/config-tools/events/networking/update_routing
		;;

	*)
		echo "Usage: ${0} {start|stop|restart}"
		exit 1
		;;
esac
