#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#
# screensaver
#

case $1 in

    start)
    	#start screend in daemon mode
        echo "Starting screend..."
        @SCREEND_START_CMD@
        echo "done."
        ;;

    stop)
        echo "Terminating screend..."
        @SCREEND_STOP_CMD@
        echo "done"
        ;;


esac
