#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#
# /etc/init.d/telecontrol
#

function event_start {
        [[ -d /etc/config-tools/events/dnp3/ ]] && run-parts -a start /etc/config-tools/events/dnp3/ >/dev/null 2>&1
        [[ -d /etc/config-tools/events/iec60870_5_104/ ]] && run-parts -a start /etc/config-tools/events/iec60870_5_104/ >/dev/null 2>&1
        [[ -d /etc/config-tools/events/iec61850_mms/ ]] && run-parts -a start /etc/config-tools/events/iec61850_mms/ >/dev/null 2>&1
}

function event_stop {
        [[ -d /etc/config-tools/events/dnp3/ ]] && run-parts -a stop /etc/config-tools/events/dnp3/ >/dev/null 2>&1
        [[ -d /etc/config-tools/events/iec60870_5_104/ ]] && run-parts -a stop /etc/config-tools/events/iec60870_5_104/ >/dev/null 2>&1
        [[ -d /etc/config-tools/events/iec61850_mms/ ]] && run-parts -a stop /etc/config-tools/events/iec61850_mms/ >/dev/null 2>&1
}

case $1 in

	start)
                event_start
		;;

	stop)
                event_stop
		;;

	restart)
                event_start
		;;

	reload)
                event_start
		;;

	*)
		echo "Usage: ${0} {start|stop|restart|reload}"
		exit 1
		;;

esac
