#!/bin/sh
#
# /etc/init.d/telnetd
#
# $Id: telnetd 7919 2008-04-06 11:31:23Z rsc $
#

if [ -f /usr/sbin/telnetd ]; then
	echo "Starting telnetd..."
	sudo /usr/sbin/telnetd
	[[ -d /etc/config-tools/events/telnet/ ]] && run-parts -a start /etc/config-tools/events/telnet/ >/dev/null 2>&1
	exit 0
fi

if [ -f /sbin/utelnetd ]; then
	echo "Starting utelnetd..."
	sudo /sbin/utelnetd -d
	[[ -d /etc/config-tools/events/telnet/ ]] && run-parts -a start /etc/config-tools/events/telnet/ >/dev/null 2>&1
	exit 0
fi

echo "No telnetd found. Aborting"

