#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021 WAGO Kontakttechnik GmbH & Co. KG
#
# webvisu filewatch script
#

case $1 in

    start)
	/etc/specific/webvisu_filewatch.sh 2>&1 > /dev/null &
	;;

    stop)
	echo "Terminating webvisu_filewatch not implemented."
	;;

esac






