#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

set -u

CONF_FILE="/etc/snmp/snmpd.conf"
USER_DEFINES_FILE="/etc/specific/snmp_user.conf"
DEFAULT_HOSTNAME=$(/etc/config-tools/determine_hostname -d)
DEFAULT_DESCR=$(/etc/config-tools/get_typelabel_value DESCR)
# Predefine entries:
USE_USER_DEFINED_DEVICE_NAME=no
USE_USER_DEFINED_DESCRIPTION=no

#if configuration file is missing create default configuration 
function write_default_config
{
  if [[ ! -e $CONF_FILE ]]; then
    cat << 'EOF' >> $CONF_FILE
rwcommunity public
authtrapenable 1
sysServices 79
sysLocation LOCAL
sysContact support@wago.com
sysObjectID .1.3.6.1.4.1.13576
EOF
  fi
}

function check_and_update
{
  local key="$1"
  local default_value="$2"
  local user_defined="$3"

  if ! egrep -q "^$key" $CONF_FILE ; then
    #if is not defined
    echo "$key $default_value" >> $CONF_FILE
  else
    if [[ "$user_defined" != yes ]]; then
      # Check if expected description is set.
      if ! egrep -q "^$key $default_value" $CONF_FILE ; then
        # Expected description is not set, therefore reset it to the expected one.
        sed -i "/$key/c\\$key $default_value" $CONF_FILE
      fi
    fi
  fi
}

case $1 in

  start)
    write_default_config

    [[ -e "$USER_DEFINES_FILE" ]] && . "$USER_DEFINES_FILE"

    check_and_update sysName "$DEFAULT_HOSTNAME" "$USE_USER_DEFINED_DEVICE_NAME"
    check_and_update sysDescr "$DEFAULT_DESCR" "$USE_USER_DEFINED_DESCRIPTION"
  ;;

  stop)
  ;;
esac
