#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG

CONF_FILE="/etc/snmp/snmpd.conf"
DEFAULT_HOSTNAME=`/etc/config-tools/determine_hostname -d`
DEFAULT_DESCR=`/etc/config-tools/get_typelabel_value DESCR`

#if configuration file is missing create default configuration 
function writeDefaultConfig()
{
    if [ ! -e $CONF_FILE ]; then
        cat << 'EOF' >> $CONF_FILE
rwcommunity  public  localhost
rwcommunity  public  192.168.2.0/24
rwcommunity public
rwcommunity private
authtrapenable 1
sysServices 79
sysLocation LOCAL
sysContact support@wago.com
sysObjectID .1.3.6.1.4.1.13576
EOF
    fi
}

case $1 in

  start)
    writeDefaultConfig

    #if sysName is not defined set hostname as default
    if [ -z "`egrep "^sysName" $CONF_FILE`" ]; then
        echo "sysName $DEFAULT_HOSTNAME" >> $CONF_FILE
    fi

    #if sysDescr is not defined use typelabel DESCR
    if [ -z "`egrep "^sysDescr" $CONF_FILE`" ]; then
        echo "sysDescr $DEFAULT_DESCR" >> $CONF_FILE
    fi
  ;;

  stop)
  ;;
esac
