#!/bin/bash
#-----------------------------------------------------------------------------#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2020-2022 WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#


set -e

case "$1" in
start)
	# settings_factory config tool will only create factory settings if necessary,
	# and returns directly if they are already saved.
	NOPV=T /etc/config-tools/settings_factory save &
	;;
stop)
	;;
*)
	echo "usage $0 start"
esac

