#!/usr/bin/env bash

###############################################################################
#  Copyright (c) WAGO GmbH & Co. KG
#
#  PROPRIETARY RIGHTS are involved in the subject matter of this material.
#  All manufacturing, reproduction, use and sales rights pertaining to this
#  subject matter are governed by the license agreement. The recipient of this
#  software implicitly accepts the terms of the license.
###############################################################################

set -e

if [ -z "$SCRIPT_DIR" ]; then
  PTXDIST_WORKSPACE="${PTXDIST_WORKSPACE:-../../../ptxproj}"
  
  PTXDIST_PLATFORMCONFIG="${PTXDIST_PLATFORMCONFIG:-$PTXDIST_WORKSPACE/selected_platformconfig}"
  PTXCONF_PLATFORM="$(source $PTXDIST_PLATFORMCONFIG && echo "$PTXCONF_PLATFORM")"
  PTXDIST_PLATFORMDIR="${PTXDIST_PLATFORMDIR:-$PTXDIST_WORKSPACE/platform-$PTXCONF_PLATFORM}"
  
  PTXCONF_SYSROOT_HOST="$(source $PTXDIST_PLATFORMCONFIG && echo "$PTXCONF_SYSROOT_HOST")"
  SYSROOT_HOST="${SYSROOT_HOST:-$PTXCONF_SYSROOT_HOST}"
    
  SCRIPT_DIR="$SYSROOT_HOST/lib/ct-build"
fi

exec "$SCRIPT_DIR/bin/ptxdist-make" "$@"
