#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG

#-----------------------------------------------------------------------------
# Script-name: adapt_netconfig_wwan
#
# Add wwan interface definition to network configuration xml file.  
# This script is called from general adapt netconfig script.
#
# Author: WAGO Kontakttechnik GmbH & Co. KG.
#-----------------------------------------------------------------------------

# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
  echo "config_tool_lib missing"
  exit 255
fi

. /etc/config-tools/config_tool_lib

NETCONFIG_FILE=/etc/specific/network-interfaces.xml
WWAN_CONFIGFILE_NAME=/etc/specific/wwan.conf

#--------------------------------------------------------------------
# help text (requested with specified parameter)
#--------------------------------------------------------------------
if [ "$1" = "-h" -o "$1" = "--help" ]; then
    echo
    echo "* Adapt network configuration xml file according to wwan configuration *"
    echo
    echo "Usage: adapt_netconfig_wwan -h | --help                 print this usage"
    echo "       adapt_netconfig_wwan [-o | --out-file <outfile>] write result to this file"
    echo
    exit 0
fi


#--------------------------------------------------------------------
# main programm
#--------------------------------------------------------------------

status=$SUCCESS

# check for missing input parameter
if [ -z "$1" ] || [ -z "$2" ]; then
  SetLastError "Missing input parameter"
  status=$MISSING_PARAMETER
  exit $status
fi

#check whether config-file exists
if [ ! -f $WWAN_CONFIGFILE_NAME ] || [ ! -f $NETCONFIG_FILE ]; then
  SetLastError "Config file is missing."
  status=$CONFIG_FILE_MISSING
  exit $status
fi

. $WWAN_CONFIGFILE_NAME
WWAN_INTERFACE_DEFINITION="\<iface\>\n\
  \<device_name\>$WWAN_DEVICE_NAME\</device_name\>\n\
  \<state\>enabled\</state\>\n\
  \<no_dsa_disable\>no\</no_dsa_disable\>\n\
  \<ip_settings\>\n\
    \<show_in_wbm\>0\</show_in_wbm\>\n\
    \<port_name\>$WWAN_PORT_NAME\</port_name\>\n\
    \<type\>dhcp\</type\>\n\
    \<gw\>\n\
      \<state\>disabled\</state\>\n\
    \</gw\>\n\
  \</ip_settings\>\n\
\</iface\>"

OUTFILE="$2"
devconf_flag_modem="$(($(/etc/config-tools/get_typelabel_value DEVCONF) & (1 << 4) ? 1 : 0 ))"
if [ "$devconf_flag_modem" == "1" ]; then
  cat $NETCONFIG_FILE | sed "/\/interfaces/i$WWAN_INTERFACE_DEFINITION" > $OUTFILE
else
  cp $NETCONFIG_FILE $OUTFILE &> /dev/null
fi

exit $status
