#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#-----------------------------------------------------------------------------#
# Script-name: cf_card_backup
#
# Process backup to or from cf-card
#
# Author: WAGO GmbH
#-----------------------------------------------------------------------------#

# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
  echo "config_tool_lib missing"
  exit 255
fi

. /etc/config-tools/config_tool_lib

status=$SUCCESS

# show help-text if requested
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo
  echo "* Process backup to or from cf-card *"
  echo
  echo "Usage: cf_card_backup"
  echo
  exit $status
fi

#echo "CF Card Backup"
sudo /usr/sbin/cp_cfcard > /dev/null 2> /dev/null #> outputs 2> errors

if [ "$?" != "$SUCCESS" ]; then
  status=$SHELL_ERROR
  ReportError $status "(/usr/sbin/cp_cfcard)"
  SetLastError "Error while copy of CF-Card"
fi

exit $status
