#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#-----------------------------------------------------------------------------#
# Script-name: change_default_webserver
#
# Change default webserver (standard or webvisu)
#
# Author: WAGO GmbH
#-----------------------------------------------------------------------------#

# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
  echo "config_tool_lib missing"
  exit 255
fi

. /etc/config-tools/config_tool_lib

restartWebserver()
{
    local restart=$1
    if [ "$restart" = "YES" ]; then
        /etc/init.d/lighttpd stop > /dev/null
        /etc/init.d/lighttpd start > /dev/null
    fi
}

#-------------- main-programm ------------------------#

status=$SUCCESS

# show help-text if requested
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo
  echo "* Change default webserver (standard or webvisu) *"
  echo
  echo "Usage: change_default_webserver default-webserver=default-webserver-value [restart-server=NO]"
  echo
  echo "default-webserver-value: \"Webserver\" | \"Webvisu\""
  echo "restart-server-value: \"YES\" | \"NO\" Default is YES"
  echo 
  exit $status
fi

# filter input parmeter of input-string
newDefaultWebserver=`GetParameterValue default-webserver $*`
restartOption=$(GetParameterValue restart-server $*)
restartOption=${restartOption:-YES}

if [ "$restartOption" != "YES" -a "$restartOption" != "NO" ]; then
    SetLastError "Invalid restart option"
    exit $INVALID_PARAMETER
fi

case "$newDefaultWebserver" in

"Webserver")    (cd /etc/lighttpd; ln -sf redirect_wbm.conf redirect_default.conf)
                restartWebserver $restartOption
                ;;

"Webvisu")
                (cd /etc/lighttpd; ln -sf redirect_webvisu.conf redirect_default.conf)
                restartWebserver $restartOption
                ;;

*)              status=$INVALID_PARAMETER
                SetLastError "Invalid default webserver"
                ;;
esac
exit $status
