#!/bin/bash
#-----------------------------------------------------------------------------#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# This file is part of PTXdist package config-tools.
#
# Copyright (c) 2012-2022 WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#
#-----------------------------------------------------------------------------#
# Script:   config_tool_defines
#
# Brief:    Global defines that may be used by hw-specific scripts
#           (i.e. in /usr/sbin).
#
# Author:   AGa: WAGO GmbH & Co. KG
# Author:   PEn: WAGO GmbH & Co. KG
# Author:   MSc: WAGO GmbH & Co. KG
# Author:   MOe: WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#

#bash "include guard"
if [[ ${CONFIG_TOOL_DEFINES_:-} != "config_tool_defines" ]]; then
readonly CONFIG_TOOL_DEFINES_="config_tool_defines"

# boolean
readonly FALSE=0
readonly TRUE=1

# errors (Nr. 1 is reserved for missing config-file)
readonly SUCCESS=0
readonly MISSING_PARAMETER=2
readonly INVALID_PARAMETER=3
readonly CONFIG_FILE_MISSING=4
readonly CONFIG_FILE_INCONSISTENT=5
readonly CONFIG_DATA_ERROR=6
readonly INTERNAL_ERROR=7
readonly SHELL_ERROR=8
readonly EXECUTABLE_ERROR=9
readonly FILE_NOT_WRITEABLE=10
readonly FILE_NOT_EXECUTABLE=11
readonly WRITE_FILE_ERROR=12
readonly NARROW_SPACE_WARNING=13
readonly NOT_ENOUGH_SPACE_ERROR=14
readonly MOUNT_ERROR=15
readonly ENCRYPTED_FILE=16

# This error is meant to be returned by board specific scripts,
# i.e. pac200_copy_data.sh to signalize that inside the script SetLastError
# has been set so that it is not overwritten by a higher-level script
readonly LAST_ERROR_SET=127
readonly LAST_ERROR_FILENAME="/tmp/last_error.txt"

# path and name of multible used executable files
readonly NETWORK_CONFIG="/etc/config-tools/network_config"

if [[ -f /etc/config-tools/board_specific_defines ]]; then
  source /etc/config-tools/board_specific_defines 
fi

fi #if [[ ${CONFIG_TOOL_DEFINES_:-} != "config_tool_defines" ]]; then
