#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#-----------------------------------------------------------------------------#
# Script-name: config_dns_service
#
# Change configuration of DNS server.
#
# Author: WAGO GmbH
#-----------------------------------------------------------------------------#

DNS_CONFIG_C="/etc/config-tools/config_dnsmasq_c -n -s"

#--------------------------------------------------------------------
# help text (requested with specified parameter)
#--------------------------------------------------------------------
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo
    echo "* Set configuration of DNS service *"
    echo
    echo "Usage: config_dns_service [ \"dns-state\"=state-value ]"
    echo "                          [ \"dns-mode\"=mode-value ]"
    echo "                          [ \"dns-fix-host\"=dns-hosts-value ]"
    echo
    echo "state-value: \"enabled\" | \"disabled\""
    echo "mode-value: \"proxy\" | \"relay\" default is proxy."
    echo "dns-hosts-value: \"<ip-addr>:hostname1[_hostnamei...],<ip-addr>:hostname1[_hostnamei...]"
    echo
    exit $SUCCESS
fi

#--------------------------------------------------------------------
# Just start the C programm. It will do all checks and actions.
#--------------------------------------------------------------------
sudo $DNS_CONFIG_C $*
exit $?
