#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#-----------------------------------------------------------------------------#
# Script-name: config_RS232
#
# Change the configuration of the serial interfaces.
#
# Author: WAGO GmbH
#-----------------------------------------------------------------------------#

# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
  echo "config_tool_lib missing"
  exit 255
fi

. /etc/config-tools/config_tool_lib

#-------------- main-programm ------------------------#

status=$SUCCESS

if [[ -e /usr/sbin/${BOARD_ID}_config_rs232.sh ]]; then
  /usr/sbin/${BOARD_ID}_config_rs232.sh $@
  status=$?
else
  # board-specific script not found
  exit $INTERNAL_ERROR
fi

exit $status
