#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#-----------------------------------------------------------------------------#
# Script-name: config_dhcpd
#
# Config Tools: Change configuration of DHCP server.
#
# Author: WAGO GmbH
#-----------------------------------------------------------------------------#

DHCPD_CONFIG_C="/etc/config-tools/config_dnsmasq_c"

#--------------------------------------------------------------------
# help text (requested with specified parameter).
#--------------------------------------------------------------------
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo
    echo "* Get and set configuration of DHCP server for a port *"
    echo
    echo "Usage: config_dhcpd [-x/--no-dnsmasq-restart] -p/--port=<port-name-value>"
    echo "                    [ \"dhcpd-state\"=state-value ]"
    echo "                    [ \"dhcpd-range\"=ranges-value ]"
    echo "                    [ \"dhcpd-lease-time\"=lease-time-value ]"
    echo "                    [ \"dhcpd-fix-host\"=fix-hosts-value ]"
    echo
    echo "-x or --no-dnsmasq-restart prevents from running /etc/init.d/dnsmasq restart"
    echo "port-name-value: a valid port name, e.g. br0"
    echo "state-value: \"enabled\" | \"disabled\""
    echo "ranges-value: <ip-addr1>_<ip-addr2>"
    echo "lease-time-value: lease time in minutes. Minimal 2. Default is 120 minutes."
    echo "fix-hosts-value: <mac-addr>_<ip-addr>,...  <mac-addr> might be a hostname."
    echo
    exit $SUCCESS
fi

#--------------------------------------------------------------------
# Just start the C programm. It will do all checks and actions.
#--------------------------------------------------------------------
sudo $DHCPD_CONFIG_C -d -s $* > /dev/null
result=$?

sync

exit $result
