#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG

#-----------------------------------------------------------------------------#
# Script-name: get_local_date
#
# Get local date. The script is needed by the C-programm, because in C we can't
# get the local date correctly with user www.
#
# Author: WAGO Kontakttechnik GmbH
#-----------------------------------------------------------------------------#

# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
  echo "config_tool_lib missing"
  exit 255
fi

. /etc/config-tools/config_tool_lib


GetDate()
#
# Get date-string for local or utc
#
{
  local timeForm=$1

  # if UTC-time should be read, set option for "time"-call accordingly 
  # in any other case (input-parameter is "local", empty or invalid) take local-time as default
  if [ "$UTC" == "$timeForm" ]; then
    timeFormOption="-u"
  else
    timeFormOption=""
  fi

  # get date-string 
  date=`/bin/date $timeFormOption +'%d.%m.%Y'`

  echo -e $date"\c"
}


#-------------- main-programm ------------------------#

source /etc/timezone

# show help-text if requested
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo
  echo "* Get local date *"
  echo
  echo "Usage: get_local_date"
  echo
  exit $status
fi


date=`GetDate local`
echo -e $date"\c"

exit $SUCCESS






