#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#-----------------------------------------------------------------------------#
# Script-name: get_user_hash
#
# Query user specific password hash or info.
#
# Author: WAGO GmbH
#-----------------------------------------------------------------------------#


# show help-text if requested
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo
  echo "* Get user specific password hash / info *"
  echo
  echo "Usage: "
  echo "       $0 --shadow-get-info [<user>]    : prints the password hash and further infos from /etc/shadow"
  echo "       $0 --shadow-get-hash [<user>]    : prints the password hash from /etc/shadow"
  echo
  exit $status
fi

# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
  echo "config_tool_lib missing"
  exit 255
fi

. /etc/config-tools/config_tool_lib

#-------------- main-programm ------------------------#

CURRENT_AUTH_FILE_LINUX="/etc/shadow"

status=$SUCCESS

#-------------- parse variables ----------------------#

case "$1" in

  "--shadow-get-info"|"--shadow-get-hash")
    login="$2"
    ;;
  *)
    status=$MISSING_PARAMETER
    SetLastError "Missing input parameter"
    ;;
esac

#-------------- get information ----------------------#

if [[ "$status" == "$SUCCESS" ]]; then

  case "$1" in

    "--shadow-get-info")
      # index returns start of the 2nd token, substr returns substring beginning with this position
      current_hash=$(awk -F: -v _login="$login" '$1~_login {print substr($0, index($0,$2))}' $CURRENT_AUTH_FILE_LINUX)
      echo $current_hash
    ;;

    "--shadow-get-hash")
      current_hash=$(awk -F: -v _login="$login" '$1~_login {print $2}' $CURRENT_AUTH_FILE_LINUX)
      echo $current_hash 
    ;;
  esac

fi

exit $status
