#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#-----------------------------------------------------------------------------#
# Script-name: get_wbm_uploads
#
# Get filenames of files, uploaded via WBM "Downloads" 
#
# Author: WAGO GmbH
#-----------------------------------------------------------------------------#

# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
  echo "config_tool_lib missing"
  exit 255
fi

. /etc/config-tools/config_tool_lib



#-------------- main-programm ------------------------#


# show help-text if requested
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo
  echo "* Get filenname of file, uploaded via WBM "Downloads" *"
  echo
  echo "Usage: get_wbm_uploads"
  echo
  exit $status
fi

# get and check input-parameter
uploadType=`GetParameterValue upload-type $*`
#echo "uploadType:"$uploadType

if [ -z "$uploadType" ]; then
  uploadType="update-script"
fi

# get content of directory (should always be only one file), cut linefeed and print (without linefeed)
printf "%s" `ls /var/downloads/$uploadType | sed 'N;s/\n/ : /'`
#ls /var/downloads/$uploadType | sed 'N;s/\n/ : /' | printf

exit $SUCCESS






