#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2020-2022 WAGO GmbH & Co. KG

#-----------------------------------------------------------------------------#
# Script-name: get_ledserver
#
# Config Tools: Get ledserver settings.
#
# Author: WAGO GmbH
#-----------------------------------------------------------------------------#

. /etc/config-tools/config_tool_lib
LED_CONFIG_FILE=/etc/specific/leds.conf


#--------------------------------------------------------------------
# help text (requested with specified parameter).
#--------------------------------------------------------------------
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo
    echo "* Get ledserver settings. *"
    echo
    echo "Usage: get_ledserver -h, --help or"
    echo "       get_ledserver frontled"
    echo
    echo "Returns \"active\" or \"inactive\""
    echo
    exit $SUCCESS
fi

#--------------------------------------------------------------------
# main - get frontled
#--------------------------------------------------------------------

status=$SUCCESS
if [ "$1" = "frontled" ]; then
    source ${LED_CONFIG_FILE}
    echo -n $FRONTLED
else
    SetLastError "Invalid input parameter ($1)"
    status=$INVALID_PARAMETER
fi

exit $status
