#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#-----------------------------------------------------------------------------#
# Script-name: get_dhcpd_config
#
# Config Tools: Get configuration of DHCPD server.
#
# Author: WAGO GmbH
#-----------------------------------------------------------------------------#

DHCPD_CONFIG_C="/etc/config-tools/config_dnsmasq_c"

#--------------------------------------------------------------------
# help text (requested with specified parameter).
#--------------------------------------------------------------------
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo
    echo "* Get configuration of DHCPD server *"
    echo
    echo "Usage: get_dhcpd_config -p, --port=<port> -g, --get-config [ dhcpd-state ] [ dhcpd-range ] [ dhcpd-lease-time ] [ dhcpd-fix-host ]"
    echo "Or     get_dhcpd_config -j, --json"
    echo 
    echo "JSON data is for all ports"
    echo
    exit $SUCCESS
fi

sudo $DHCPD_CONFIG_C -d $*

