#!/bin/bash
#-----------------------------------------------------------------------------#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2022 WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#
#-----------------------------------------------------------------------------#
# Script:   restart_webserver
#
# Brief:    Restart standard webserver after timeout.
#
# Author:   SM:  WAGO GmbH & Co. KG
# Author:   AGa: WAGO GmbH & Co. KG
# Author:   HJH: WAGO GmbH & Co. KG
# Author:   PEn: WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#

# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
  echo "config_tool_lib missing"
  exit 255
fi

. /etc/config-tools/config_tool_lib

LIGHTTPD_START_LINK=/etc/rc.d/@LIGHTTPD_BBINIT_LINK@

#-------------- main-programm ------------------------#

status=$SUCCESS

# show help-text if requested
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo
  echo "* Restart standard webserver *"
  echo
  echo "Usage: restart_webserver [ timout in seconds ]"
  echo
  exit $status
fi

if [ -h $LIGHTTPD_START_LINK ]; then
  timeoutInSec=$1

  if [ -z "$timeoutInSec" ]; then
    timeoutInSec=0
  fi

  sleep $timeoutInSec
  /etc/init.d/lighttpd stop > /dev/null 2> /dev/null
  /etc/init.d/lighttpd start > /dev/null 2> /dev/null
fi

exit $status
