#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2020-2022 WAGO GmbH & Co. KG

#-----------------------------------------------------------------------------
# Script-name: set_dsa_mode
#
# Calls C program to set eth switch configuration.
#
# Author: HJH, WAGO GmbH & Co. KG.
#         StB, WAGO GmbH & Co. KG.
#         MOe, WAGO GmbH & Co. KG.
#-----------------------------------------------------------------------------

# set error on use of undefined shell variables
set -u

dsa_mode=""

# main program

# Load general definitions and functions.
CTDIR=/etc/config-tools
if [ ! -f "$CTDIR/config_tool_lib" ]; then
    echo "config_tool_lib missing"
    exit 64
fi
. $CTDIR/config_tool_lib

# show help-text if requested
if [ $# -gt 0 ]; then
    if [ "$1" = "-h" -o "$1" = "--help" ]; then
        echo
        echo "* Change network switch configuration *"
        echo
        echo "Usage: set_dsa_mode -h | --help         print this usage"
        echo "       set_dsa_mode -v|--value <value>  set separated resp. switched interface mode"
        echo
        echo "<value> = 0   set switched interface mode"
        echo "<value> = 1     set separated interface mode"
        exit 0
    fi

    if [ "$1" = "-v" -o "$1" = "--value" ]; then
        if [ "$#" -ge "2" ]; then
            dsa_mode="$2"
            shift 2
        fi
    fi
fi

if [ -z "$dsa_mode" ]; then
    SetLastError "set_dsa_mode: missing argument"
    exit $MISSING_PARAMETER
fi

$NETWORK_CONFIG --dsa-mode --set $dsa_mode
status=$?

exit $status

