#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#-----------------------------------------------------------------------------#
# Script-name: start_reboot
#
# Start reboot.
#
# Author: WAGO GmbH
#-----------------------------------------------------------------------------#

# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
  echo "config_tool_lib missing"
  exit 255
fi

. /etc/config-tools/config_tool_lib

status=$SUCCESS

# show help-text if requested
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo
  echo "* Start reboot *"
  echo
  echo "Usage: start_reboot"
  echo
  exit $status
fi

# if script is called by webserver, give him time to show the next page accurate before we filch the processor
if [ "$1" = "web" ]; then
  sleep 5
fi

sudo /sbin/reboot

if [ "$SUCCESS" != "$?" ]; then
  status=$SHELL_ERROR
  ReportError $status "(reboot)"
  SetLastError "Error while execution"
fi

exit $status
