#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2019 WAGO Kontakttechnik GmbH & Co. KG

RUNDIR="/var/run/netconfd"
PIDFILE="netconfd.pid"
PATHPIDFILE=$RUNDIR/$PIDFILE
NETCONFD="/usr/bin/netconfd"
STARTCMD="$NETCONFD --daemon --rundir=$RUNDIR --pidfile=$PIDFILE --loglevel=warning"

set -e

function stop_netconfd {
    start-stop-daemon --stop --pidfile $PATHPIDFILE --retry=TERM/20/KILL/10 --oknodo --exec $NETCONFD
    /usr/bin/rm -f $PATHPIDFILE
}


case $1 in
start)
    $STARTCMD
    echo "done"
    ;;

stop)
    echo "Stopping network configuration daemon"
    stop_netconfd
    ;;

restart)
    echo "Restart network configuration daemon"
    stop_netconfd
    $STARTCMD
    echo "done"
    ;;

*)
    echo "Usage $0 start | stop | restart"
esac
