#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2019 WAGO Kontakttechnik GmbH & Co. KG

RUNDIR="/var/run/netconfd"
PIDFILE="netconfd.pid"
PATHPIDFILE=$RUNDIR/$PIDFILE
NETCONFD="/usr/bin/netconfd"
STARTCMD="$NETCONFD --daemon --rundir=$RUNDIR --pidfile=$PIDFILE"

set -e

function stop_netconfd {
    start-stop-daemon --stop --pidfile $PATHPIDFILE --retry=TERM/20/KILL/10 --oknodo --exec $NETCONFD
    /usr/bin/rm -f $PATHPIDFILE
}

function wait_for_netconfd_ready {
   dbus-wait -t 30 de.wago.netconfd
   if [ $? != 0 ]; then
     logger -t netconfd.init.d "ERROR: netconfd: DBUS interface de.wago.netconfd not reachable!"
     exit -1
   fi
}

case $1 in
start)
    $STARTCMD
    wait_for_netconfd_ready
    echo "done"
    ;;

stop)
    echo "Stopping network configuration daemon"
    stop_netconfd
    ;;

restart)
    echo "Restart network configuration daemon"
    stop_netconfd
    $STARTCMD
    wait_for_netconfd_ready
    echo "done"
    ;;

*)
    echo "Usage $0 start | stop | restart"
esac
