#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG

# Restart dnsmasq on network interface configuration changes.
# Only restart dnsmasq if it is already running.
# $(Id)
# Hoffmann, Hans-Josef

if pidof dnsmasq > /dev/null; then
    sudo /etc/init.d/dnsmasq restart > /dev/null
fi

