#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

SOURCE=`grep -m1 -o "root=/dev/[[:alpha:]][[:alpha:]][[:alpha:]]" /proc/cmdline | grep -m1 -o "/dev/[[:alpha:]][[:alpha:]][[:alpha:]]"`

if [ "$SOURCE" = "/dev/hda" ]; then
    DEST="/dev/hdb"
else
    DEST="/dev/hda"
fi

#echo $DEST
#echo $SOURCE

sudo /usr/sbin/update_mbr_grub $SOURCE $DEST
sudo /usr/sbin/update_boot $SOURCE $DEST 
sudo /usr/sbin/update_fw $SOURCE $DEST
sudo /usr/sbin/create_home_int $SOURCE $DEST