#!/bin/bash
#-----------------------------------------------------------------------------#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# This file is part of PTXdist package wago-custom-install.
#
# Copyright (c) 2018-2019 WAGO Kontakttechnik GmbH & Co. KG
#-----------------------------------------------------------------------------#
#-----------------------------------------------------------------------------#
# Script:   settings_backup_lib
#
# Brief:    General definitions and functions for the backup and restore
#
# Author:   StM: WAGO Kontakttechnik GmbH & Co. KG
# Author:   AGa: WAGO Kontakttechnik GmbH & Co. KG
# Author:   HJH: WAGO Kontakttechnik GmbH & Co. KG
# Author:   MOe: WAGO Kontakttechnik GmbH & Co. KG
# Author:   OG:  WAGO Kontakttechnik GmbH & Co. KG
# Author:   MSc: WAGO Kontakttechnik GmbH & Co. KG
#-----------------------------------------------------------------------------#

# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
  echo "config_tool_lib missing"
  exit 64
fi

source /etc/config-tools/config_tool_lib

progressFile=/tmp/progressFile.tmp

BACKUP_RESTORE_SCRIPT_DIR="/etc/config-tools/backup-restore"


declare -i restore_error_count=0
declare -i backup_error_count=0

RELEASE_VERSION=yes

SuppressMessageOutput()
{
  exec 4>&2               # save stderr to 4
  exec 3>&1               # save stdout to 3
  exec > /dev/null 2>&1   # now, suppress all messages
}

RestoreMessageOutput()
{
  exec 2>&4 # restore stderr
  exec 1>&3 # restore stdout
}

# Check if the current firmware version is greater than the given version.
#
# Param 1: minimal major version
# Param 2: minimal minor version
# Param 3: minimal bugfix version
#
# Return: 0 if the current fw version is greater than the given fw version,
#         1 otherwise.
#-----------------------------------------------------------------------------#
IsMinTargetVersion()
{
  local MIN_MAJOR=$1
  local MIN_MINOR=$2
  local MIN_BUGFIX=$3
  local RESULT=1
  
  if [[ -n "${WAGO_BACKUP_TARGET_VERSION:-}" ]] ; then
  
    local MAJOR
    MAJOR=$(echo -n $WAGO_BACKUP_TARGET_VERSION | cut -d'.' -f1)
    local MINOR
    MINOR=$(echo -n $WAGO_BACKUP_TARGET_VERSION | cut -d'.' -f2)
    local BUGFIX
    BUGFIX=$(echo -n $WAGO_BACKUP_TARGET_VERSION | cut -d'.' -f3 | cut -d'(' -f1)

    if [[ ${MAJOR#0*} -gt $MIN_MAJOR || ( ${MAJOR#0*} -eq $MIN_MAJOR && ${MINOR#0*} -gt $MIN_MINOR ) || ( ${MAJOR#0*} -eq $MIN_MAJOR && ${MINOR#0*} -eq $MIN_MINOR && ${BUGFIX#0*} -ge $MIN_BUGFIX ) ]]; then
      RESULT=0
    fi
  else
    RESULT=0
  fi
  
  return $RESULT
}


IsNetworkSettingsV2()
{
  IsMinTargetVersion 3 3 0
}

# list of the parameters which configuration should be saved
# one line with 3 parts for each parameter, parts seperated by ';'
# 1. part: name of parameter to identify it in backup file
# 2. part: executable to read the parameter value
# 3. part: executable to write the parameter value (value will be added at the end of the string

configParam=()

if ! IsNetworkSettingsV2 ; then
  configParam+=(
    "dsa-mode;                $NETWORK_CONFIG --get --dsa-mode --quiet;                         $NETWORK_CONFIG --dsa-mode --quiet --set "
  )
fi

configParam+=(
  "hostname;                  /etc/config-tools/get_coupler_details hostname;                   /etc/config-tools/change_hostname hostname="
  "domain-name;               /etc/config-tools/get_coupler_details domain-name;                /etc/config-tools/edit_dns_server domain-name="
  "default-gw-1-state;        /etc/config-tools/get_default_gateway_config number=1 state;      /etc/config-tools/config_default_gateway number=1 state="
  "default-gw-1-ipaddr;       /etc/config-tools/get_default_gateway_config number=1 value;      /etc/config-tools/config_default_gateway number=1 value="
  "default-gw-1-metric;       /etc/config-tools/get_default_gateway_config number=1 metric;     /etc/config-tools/config_default_gateway number=1 metric="
  "default-gw-1-destination;  /etc/config-tools/get_default_gateway_config number=1 destination; /etc/config-tools/config_default_gateway number=1 destination="
  "default-gw-1-dest_mask;    /etc/config-tools/get_default_gateway_config number=1 dest_mask;  /etc/config-tools/config_default_gateway number=1 dest_mask="
  "default-gw-2-state;        /etc/config-tools/get_default_gateway_config number=2 state;      /etc/config-tools/config_default_gateway number=2 state="
  "default-gw-2-ipaddr;       /etc/config-tools/get_default_gateway_config number=2 value;      /etc/config-tools/config_default_gateway number=2 value="
  "default-gw-2-metric;       /etc/config-tools/get_default_gateway_config number=2 metric;     /etc/config-tools/config_default_gateway number=2 metric="
  "default-gw-2-destination;  /etc/config-tools/get_default_gateway_config number=2 destination; /etc/config-tools/config_default_gateway number=2 destination="
  "default-gw-2-dest_mask;    /etc/config-tools/get_default_gateway_config number=2 dest_mask;  /etc/config-tools/config_default_gateway number=2 dest_mask="

  "codesys-version;           /etc/config-tools/get_runtime_config running-version;             /etc/config-tools/config_runtime --wait force-new-version=yes runtime-version="
  "codesys-homedir-sdcard;    /etc/config-tools/get_runtime_config homedir-on-sdcard;           /etc/config-tools/config_runtime homedir-on-sdcard="

  "switch-port-mirror;        /etc/config-tools/get_switch_settings port-mirror;                /etc/config-tools/config_switch --port-mirror="
  "switch-bcast-protect;      /etc/config-tools/get_switch_settings bcast-protect;              /etc/config-tools/config_switch --bcast-protect="
  "switch-fast-aging;         /etc/config-tools/get_switch_settings fast-aging;                 /etc/config-tools/config_switch --fast-aging="
  "switch-rate-limit;         /etc/config-tools/get_switch_settings rate-limit;                 /etc/config-tools/config_switch --rate-limit="

  "ntp-port;                  /etc/config-tools/get_ntp_config port;                            /etc/config-tools/config_sntp port="
  "ntp-timeserver;            /etc/config-tools/get_ntp_config time-server-1;                   /etc/config-tools/config_sntp time-server-1="
  "ntp-timeserver-2;          /etc/config-tools/get_ntp_config time-server-2;                   /etc/config-tools/config_sntp time-server-2="
  "ntp-timeserver-3;          /etc/config-tools/get_ntp_config time-server-3;                   /etc/config-tools/config_sntp time-server-3="
  "ntp-timeserver-4;          /etc/config-tools/get_ntp_config time-server-4;                   /etc/config-tools/config_sntp time-server-4="
  "ntp-update-time;           /etc/config-tools/get_ntp_config update-time;                     /etc/config-tools/config_sntp update-time="
  "ntp-state;                 /etc/config-tools/get_ntp_config state;                           /etc/config-tools/config_sntp state="

  "service-interface-owner;   /etc/config-tools/get_service_interface_config mode -b;           /etc/config-tools/config_service_interface mode="
  "rs232Owner;                /etc/config-tools/get_coupler_details RS232-owner;                /etc/config-tools/config_RS232 owner="
  "telnet-state;              /etc/config-tools/get_port_state telnet;                          /etc/config-tools/config_port port=telnet state="
  "codesys-webserver-state;   /etc/config-tools/get_runtime_config cfg-version=2 webserver-state; /etc/config-tools/config_runtime cfg-version=2 webserver-state="
  "codesys3-webserver-state;  /etc/config-tools/get_runtime_config cfg-version=3 webserver-state; /etc/config-tools/config_runtime cfg-version=3 webserver-state="
  "ftp-state;                 /etc/config-tools/config_ssl ftp-status;                          /etc/config-tools/config_port port=ftp state="
  "ftps-state;                /etc/config-tools/config_ssl ftps-status;                         /etc/config-tools/config_port port=ftps state="
  "codesys-port-state;        /etc/config-tools/get_runtime_config service-state;               /etc/config-tools/config_runtime cfg-version=2 service-state="
  "codesys-port-number;       /etc/config-tools/get_runtime_config comm-port;                   /etc/config-tools/config_runtime cfg-version=2 comm-port="

  "ssh-state;                 /etc/config-tools/get_ssh_config state;                           /etc/config-tools/config_ssh state="
  "ssh-port-nr;               /etc/config-tools/get_ssh_config port-number;                     /etc/config-tools/config_ssh port-number="
  "ssh-root-login;            /etc/config-tools/get_ssh_config root-access-state;               /etc/config-tools/config_ssh root-access-state="
  "ssh-pwd-login;             /etc/config-tools/get_ssh_config password-request-state;          /etc/config-tools/config_ssh password-request-state="

  "http-state;                /etc/config-tools/config_ssl http-status;                         /etc/config-tools/config_port port=http  state="
  "https-state;               /etc/config-tools/config_ssl https-status;                        /etc/config-tools/config_port port=https state="
  "https-cipher-list;         /etc/config-tools/get_https_tls_config cipher-list;               /etc/config-tools/config_https_tls cipher-list="

  "tftp-state;                /etc/config-tools/get_tftp_config state;                          /etc/config-tools/config_tftp state="
  "tftp-dl-dir;               /etc/config-tools/get_tftp_config download-dir;                   /etc/config-tools/config_tftp download-dir="

  "codesys-port-auth;         /etc/config-tools/get_rts3scfg_value PASSWORD USEPWD;             /etc/config-tools/config_runtime cfg-version=2 authentication="
  "codesys3-port-auth;        /etc/config-tools/get_runtime_config cfg-version=3 authentication; /etc/config-tools/config_runtime cfg-version=3 authentication="

  "opcua-state;               /etc/config-tools/config_opcua state;                             /etc/config-tools/config_opcua state="

  "default-webserver;         /etc/config-tools/get_coupler_details default-webserver;          /etc/config-tools/config_runtime default-webpage="
  "snmp-general-state;        /etc/config-tools/get_port_state snmp;                            /etc/config-tools/config_snmp set-snmp="
  "snmp-device-name;          /etc/config-tools/get_snmp_data device-name;                      /etc/config-tools/config_snmp device-name="
  "snmp-description;          /etc/config-tools/get_snmp_data description;                      /etc/config-tools/config_snmp description="
  "snmp-physical-location;    /etc/config-tools/get_snmp_data physical-location;                /etc/config-tools/config_snmp physical-location="
  "snmp-contact;              /etc/config-tools/get_snmp_data contact;                          /etc/config-tools/config_snmp contact="
  "snmp-objectid;             /etc/config-tools/get_snmp_data objectID;                         /etc/config-tools/config_snmp objectID="
  "snmp-v1-v2-state;          /etc/config-tools/get_snmp_data v1-v2c-state;                     /etc/config-tools/config_snmp v1-v2c-state="
  "snmp-v1-v2-community-name; /etc/config-tools/get_snmp_data v1-v2c-community-name;            /etc/config-tools/config_snmp v1-v2c-community-name="
#  "screensaver-state;         /etc/config-tools/get_rts3scfg_value SCREENSAVER state;           /etc/config-tools/change_rts_config area=SCREENSAVER state="
#  "screensaver-waittime;      /etc/config-tools/get_rts3scfg_value SCREENSAVER WaitTime;        /etc/config-tools/change_rts_config area=SCREENSAVER WaitTime="
#  "cleanmode-timeout;         /etc/config-tools/get_rts3scfg_value CLEANMODE Timeout;           /etc/config-tools/change_rts_config area=CLEANMODE Timeout="

  "clock-display-mode;        /etc/config-tools/get_clock_data display-mode;                    /etc/config-tools/config_clock_display_mode display-mode="
  "clock-tz-string;           /etc/config-tools/get_clock_data tz-string;                       /etc/config-tools/config_timezone tz-string="

  "modbus-tcp-state;          /etc/config-tools/modbus_config get tcp enabled;                 /etc/config-tools/modbus_config set tcp enabled "
  "modbus-udp-state;          /etc/config-tools/modbus_config get udp enabled;                 /etc/config-tools/modbus_config set udp enabled "
  "modbus-alt-watchdog-enabled; /etc/config-tools/modbus_config get alternative-watchdog enabled; /etc/config-tools/modbus_config set alternative-watchdog enabled "
  "modbus-alt-watchdog-timeout; /etc/config-tools/modbus_config get alternative-watchdog timeout; /etc/config-tools/modbus_config set alternative-watchdog timeout "
  "modbus-alt-watchdog-options; /etc/config-tools/modbus_config get alternative-watchdog options; /etc/config-tools/modbus_config set alternative-watchdog options "

  "profibus-dp-ssa-user;      /etc/config-tools/pbdp_config get ssa.user ssa_released;          /etc/config-tools/pbdp_config set ssa.user ssa_released "
  
  "iocheck-port;              /etc/config-tools/get_iocheckport_config state;                   /etc/config-tools/config_iocheckport state="
  
  "sim-pin;                   /etc/config-tools/settings_backup_mdmd backup sim-pin;            /etc/config-tools/settings_backup_mdmd restore sim-pin "
  "port-state;                /etc/config-tools/settings_backup_mdmd backup port-state;         /etc/config-tools/settings_backup_mdmd restore port-state "
  "log-level;                 /etc/config-tools/settings_backup_mdmd backup log-level;          /etc/config-tools/settings_backup_mdmd restore log-level "

  "gprs-auth-type;            /etc/config-tools/settings_backup_mdmd backup gprs-auth-type;     /etc/config-tools/settings_backup_mdmd restore dummy "
  "gprs-username;             /etc/config-tools/settings_backup_mdmd backup gprs-username;      /etc/config-tools/settings_backup_mdmd restore dummy " 
  "gprs-apn;                  /etc/config-tools/settings_backup_mdmd backup gprs-apn;           /etc/config-tools/settings_backup_mdmd restore dummy "
  "gprs-connectivity;         /etc/config-tools/settings_backup_mdmd backup gprs-connectivity;  /etc/config-tools/settings_backup_mdmd restore gprs-connectivity "
  "net-selection-mode;        /etc/config-tools/settings_backup_mdmd backup net-selection-mode; /etc/config-tools/settings_backup_mdmd restore net-selection-mode " 
  )


GetPortsList ()
{
  echo "$(GetLegacyPorts)"
}


# Function to process of an error after restory operation.
#
# If returned value of the last restore operation is not SUCCESS, then error text, 
# name of erroneous parameter and last error text (if it is found) will be logged 
# and global error counter will be incremented. 
#
# Param 1: returned value of last restore operation 
# Param 2: error text
# Param 3: name of erroneous parameter 
#
# Return: 0 (success)
#-----------------------------------------------------------------------------#
ProcessErrRestoreOperation ()
{
  local errorCode=$1
  local errorText="$2"
  local errorParam="$3"
  local lastError=""
  if [[ "$errorCode" != "$SUCCESS" ]]; then
     if [[ -f "$LAST_ERROR_FILENAME" ]]; then
       read lastError < "$LAST_ERROR_FILENAME"
     fi
     if [ -n "$lastError" ]; then
        ReportError $errorCode "$errorText  \"$errorParam\" \"$lastError\""
     else
        ReportError $errorCode "$errorText  \"$errorParam\""
     fi   
     restore_error_count=$((restore_error_count+1))
  fi
  return 0
}

# Function to process of an error after backup operation.
#
# If returned value of the last backup operation is not SUCCESS, then error text, 
# name of erroneous parameter and last error text (if it is found) will be logged 
# and global error counter will be incremented. 
#
# Param 1: returned value of last restore operation 
# Param 2: error text
# Param 3: name of erroneous parameter 
#
# Return: 0 (succsess)
#-----------------------------------------------------------------------------#
ProcessErrBackupOperation ()
{
  local errorCode=$1
  local errorText="$2"
  local errorParam="$3"
  local lastError=""
  
  if [[ "$errorCode" != "$SUCCESS" ]]; then 
     if [[ -f "$LAST_ERROR_FILENAME" ]]; then
        read lastError < "$LAST_ERROR_FILENAME"
     fi
     if [ -n "$lastError" ]; then
        ReportError $errorCode "$errorText  \"$errorParam\" \"$lastError\""
     else
        ReportError $errorCode "$errorText  \"$errorParam\""
     fi  
     backup_error_count=$((backup_error_count+1))
  fi
  return 0
}

# TODO: use this function in "settings_backup_vpn" script too.

# Function to backup a know file with output to stdout.
#
# Param 1: parameter key in backup file
# Param 2: name of file to backup

# Return: 0 (succsess)
#         CONFIG_FILE_MISSING (config file not found)
#-----------------------------------------------------------------------------#
BackupKnownFile()
{
  local RESULT=0
  local KEY=$1
  local FILE="$2"
  
  if [[ -f "$FILE" ]]; then
      base64 "$FILE" | awk "\$0=\"$KEY=\"\$0"
  else
      RESULT=$CONFIG_FILE_MISSING
  fi

  return $RESULT
}
