#!/bin/sh

set -e
cd /etc/dropbear

/usr/sbin/random_seed

while read type size md5; do
  key="dropbear_${type}_host_key"
  key_md5="$(md5sum < "$key" 2>/dev/null)"
  if [ ! -f "$key" ] || [ "$md5" = "${key_md5%% *}" ]; then
    dropbearkey -t "$type" -s "$size" -f "${key}.tmp" &&
      mv "${key}.tmp" "${key}"
  fi
done << EOF
ecdsa 521 eac949a3ca2e6e70e5992caffbde7197
dss 1024 fa1916278bbbd44e145739677cf77b18
rsa 2048 47933d6da5f16c79d9cd1cf8a6994f8c
EOF

exec sync
