#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG

DESTX=`echo "$2""*"`

#SOUCRE=$1 
#DEST=$2

echo "Copying MBR and grub partition from $1->$2"
/bin/umount $DESTX > /dev/null 2>&1
dd if=$1 of=$2 bs=512 count=300 > /dev/null 2>&1
sync
/usr/sbin/rereadpart $2
echo "done"

