#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG

#SOURCE=$1 
#DEST=$2

SOURCE3=`echo "$1""3"`
DEST3=`echo "$2""3"`
#echo SOURCE3 $SOURCE3 
#echo DEST3 $DEST3

echo "Creating root partition $2..."
sudo /bin/umount $DEST3 > /dev/null 2>&1
#sudo /usr/bin/flock /etc/rootpartition /usr/sbin/sfdisk --force -N1 -uB -C 15 -S 63 -H 256 $2 < /etc/rootpartition > /dev/null 2>&1
echo "Copying root partition $SOURCE3->$DEST3..."
dd if=$SOURCE3 of=$DEST3 > /dev/null 2>&1
sync
echo "done"

