#!/bin/bash
#-----------------------------------------------------------------------------#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2019-2022 WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#
#-----------------------------------------------------------------------------#
# Script:   backup_netconfd
#
# Brief:    Backup and restore network configuration accessed by netconfd.
#
# Author:   StB: WAGO GmbH & Co. KG
# Author:   MOe: WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#

set -u

CONFIG_TOOL=/etc/config-tools/network_config

# load common backup/restore functions
if [ ! -f "/usr/sbin/settings_backup_lib" ]; then
  echo "settings_backup_lib missing"
  exit 64	
fi

BACKUP_TARGET_VERSION_PARAM=
if [ -n "${WAGO_BACKUP_TARGET_VERSION:-}" ]; then
	BACKUP_TARGET_VERSION_PARAM="--backup-targetversion ${WAGO_BACKUP_TARGET_VERSION:-}"
fi

source /usr/sbin/settings_backup_lib

GetParameterCount()
{
    local status=0
    local dbus_out=""
    
    out=$($CONFIG_TOOL --get-backup-parameter-count)
    status=$?
    echo "$out"
    
    return $status
}

Save()
{
    local status=0
    if IsNetworkSettingsV2 ; then
	    local file_path="$1"
	
	    out=$($CONFIG_TOOL --backup "${file_path}" $BACKUP_TARGET_VERSION_PARAM )
	    status=$?
	    echo "$out"
    fi
	  return $status
}

Restore()
{
    local file_path="$1"
    local status=0

    out=$($CONFIG_TOOL --restore "${file_path}")
    status=$?
    echo "$out"
    return $status
}

PrintUsage()
{
    echo "backup_netconfd --save <backup-file>      backup routing parameters"
    echo "backup_netconfd --restore <backup-file>   restore routing parameters"
    echo "backup_netconfd --param-count             get number of routing parameters to save"
}


#### MAIN ##########################################################################################

status=0

if [[ $# -ge 1 ]]; then
    operation=$1

    if [[ $# -ge 2 ]]; then
        if [[ "$2" = /* ]]; then
            file="$2"
        else
            file="$(pwd)/$2"
        fi
        
        if [[ -e "$file" ]]; then
            if [[ "$operation" == "--save" ]]; then
                Save "$file"
                status=$?
            elif [[ "$operation" == "--restore" ]]; then
                Restore "$file"
                status=$?
            else
                # Unknown operation
                status=1
            fi
        else
            # File does not exist.
            logger -t backup_netconfd "backup file does not exist."
            #Invalid parameter
            status=3
        fi
    else
        if [[ "$operation" == "--param-count" ]]; then
            GetParameterCount
        elif [[ "$operation" == "-h" || "$operation" == "--help" ]]; then
            PrintUsage
        else
            # Unknown operation
            status=1
        fi
    fi
fi

if [[ $status != 0 ]]; then
    logger -t backup_netconfd "BackupRestore operation failed"
fi

exit $status
