#!/usr/bin/env bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG

# new hw

test_emmc_to_sd_enough_space()
{
    assertTrue "sd card must exist"     "[[ -b /dev/mmcblk0 ]]"
    assertTrue "emmc card must exist"   "[[ -b /dev/mmcblk1 ]]"

#    if [[ "$(/etc/config-tools/get_filesystem_data get-active-device)" != "/dev/mmcblk1" ]]; then
#        startSkipping
#    fi

    /etc/config-tools/copy_firmware_image source-medium=internal-flash-emmc destination-medium=sd-card action=nand-check-size
    status="$?"

    assertTrue "Space on sd card should suffice for copying" $status

#    if [[ "$(/etc/config-tools/get_filesystem_data get-active-device)" != "/dev/mmcblk1" ]]; then
#        endSkipping
#    fi
}


test_emmc_to_sd_not_enough_space()
{
    assertTrue "sd card must exist"     "[[ -b /dev/mmcblk0 ]]"
    assertTrue "emmc card must exist"   "[[ -b /dev/mmcblk1 ]]"

#    if [[ "$(/etc/config-tools/get_filesystem_data get-active-device)" != "/dev/mmcblk1" ]]; then
#        startSkipping
#    fi

    sd_card_size_kb=$(/etc/config-tools/get_device_data size /dev/mmcblk0)

    dd if=/dev/zero bs="$sd_card_size_kb" count=1024 | pv --name "Create a big file" --size $((sd_card_size_kb * 1024)) > /home/bigfile

    /etc/config-tools/copy_firmware_image source-medium=internal-flash-emmc destination-medium=sd-card action=nand-check-size
    status="$?"

    assertTrue "Space on sd card should not suffice for copying" "[[ $status == 14 ]]" # NOT_ENOUGH_SPACE_ERROR

    rm -f /home/bigfile

#    if [[ "$(/etc/config-tools/get_filesystem_data get-active-device)" != "/dev/mmcblk1" ]]; then
#        endSkipping
#    fi

}

. shunit2

