#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#
# Firewall: ssh demon events handler
#

enabled=`/etc/config-tools/firewall firewall --is-enabled`
[ "enabled" != "$enabled" ] && exit 0


start()
{
    running=`/etc/config-tools/get_ssh_config state`
    nport=`/etc/config-tools/get_ssh_config port-number`
    cport=`/usr/bin/xmlstarlet sel -N f=http://www.wago.com/security/firewall -T -t -v "/f:firewall/f:ipv4/f:service/f:rules/f:rule/@dst_port" /etc/firewall/services/ssh.xml`

    if [ "enabled" == "$running" ] ; then
        action="up"
    else
        action="down"
    fi

    if [ "x${nport}" == "x${cport}" ] ; then
        update=""
    else
        update="--upd-rule 1 on tcp - ${nport} "
    fi

    /etc/config-tools/firewall ssh ${update}--apply ${action} >/dev/null 2>&1
}

stop()
{
    /etc/config-tools/firewall ssh --apply down >/dev/null 2>&1
}

case "$1" in
    start|config)
        start;;
    stop)
        stop;;
    *)
        ;;
esac
