#!/bin/bash
#-----------------------------------------------------------------------------#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# This file is part of PTXdist package wago-custom-install.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#
#-----------------------------------------------------------------------------#
# Script:   settings_backup_lib
#
# Brief:    General definitions and functions for the backup and restore
#
# Author:   StM: WAGO GmbH & Co. KG
# Author:   AGa: WAGO GmbH & Co. KG
# Author:   HJH: WAGO GmbH & Co. KG
# Author:   MOe: WAGO GmbH & Co. KG
# Author:   OG: WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#

# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
  echo "config_tool_lib missing"
  exit 64
fi

source /etc/config-tools/config_tool_lib

progressFile=/tmp/progressFile.tmp

BACKUP_RESTORE_SCRIPT_DIR="/etc/config-tools/backup-restore"


declare -i restore_error_count=0
declare -i backup_error_count=0

RELEASE_VERSION=yes

SuppressMessageOutput()
{
  exec 4>&2               # save stderr to 4
  exec 3>&1               # save stdout to 3
  exec > /dev/null 2>&1   # now, suppress all messages
}

RestoreMessageOutput()
{
  exec 2>&4 # restore stderr
  exec 1>&3 # restore stdout
}


# list of the parameters which configuration should be saved
# one line with 3 parts for each parameter, parts seperated by ';'
# 1. part: name of parameter to identify it in backup file
# 2. part: executable to read the parameter value
# 3. part: executable to write the parameter value (value will be added at the end of the string

#FIXME: read dsa mode properly
configParam=(     
  "dsa-mode;                  /usr/bin/xmlstarlet sel -t -m //dsa_mode -v . /etc/specific/network-interfaces.xml; /etc/config-tools/set_dsa_mode --value "
  "hostname;                  /etc/config-tools/get_coupler_details hostname;                   /etc/config-tools/change_hostname hostname="
  "domain-name;               /etc/config-tools/get_coupler_details domain-name;                /etc/config-tools/edit_dns_server domain-name="
  "default-gw-1-state;        /etc/config-tools/get_default_gateway_config number=1 state;      /etc/config-tools/config_default_gateway number=1 state="
  "default-gw-1-ipaddr;       /etc/config-tools/get_default_gateway_config number=1 value;      /etc/config-tools/config_default_gateway number=1 value="
  "default-gw-1-metric;       /etc/config-tools/get_default_gateway_config number=1 metric;     /etc/config-tools/config_default_gateway number=1 metric="
  "default-gw-1-destination;  /etc/config-tools/get_default_gateway_config number=1 destination; /etc/config-tools/config_default_gateway number=1 destination="
  "default-gw-1-dest_mask;    /etc/config-tools/get_default_gateway_config number=1 dest_mask;  /etc/config-tools/config_default_gateway number=1 dest_mask="
  "default-gw-2-state;        /etc/config-tools/get_default_gateway_config number=2 state;      /etc/config-tools/config_default_gateway number=2 state="
  "default-gw-2-ipaddr;       /etc/config-tools/get_default_gateway_config number=2 value;      /etc/config-tools/config_default_gateway number=2 value="
  "default-gw-2-metric;       /etc/config-tools/get_default_gateway_config number=2 metric;     /etc/config-tools/config_default_gateway number=2 metric="
  "default-gw-2-destination;  /etc/config-tools/get_default_gateway_config number=2 destination; /etc/config-tools/config_default_gateway number=2 destination="
  "default-gw-2-dest_mask;    /etc/config-tools/get_default_gateway_config number=2 dest_mask;  /etc/config-tools/config_default_gateway number=2 dest_mask="

  "codesys-version;           /etc/config-tools/get_runtime_config running-version;             /etc/config-tools/config_runtime --wait force-new-version=yes runtime-version="
  "codesys-homedir-sdcard;    /etc/config-tools/get_runtime_config homedir-on-sdcard;           /etc/config-tools/config_runtime homedir-on-sdcard="

  "switch-port-mirror;        /etc/config-tools/get_switch_settings port-mirror;                /etc/config-tools/config_switch --port-mirror="
  "switch-bcast-protect;      /etc/config-tools/get_switch_settings bcast-protect;              /etc/config-tools/config_switch --bcast-protect="
  "switch-fast-aging;         /etc/config-tools/get_switch_settings fast-aging;                 /etc/config-tools/config_switch --fast-aging="
  "switch-rate-limit;         /etc/config-tools/get_switch_settings rate-limit;                 /etc/config-tools/config_switch --rate-limit="

  "ntp-port;                  /etc/config-tools/get_ntp_config port;                            /etc/config-tools/config_sntp port="
  "ntp-timeserver;            /etc/config-tools/get_ntp_config time-server-1;                   /etc/config-tools/config_sntp time-server-1="
  "ntp-timeserver-2;          /etc/config-tools/get_ntp_config time-server-2;                   /etc/config-tools/config_sntp time-server-2="
  "ntp-timeserver-3;          /etc/config-tools/get_ntp_config time-server-3;                   /etc/config-tools/config_sntp time-server-3="
  "ntp-timeserver-4;          /etc/config-tools/get_ntp_config time-server-4;                   /etc/config-tools/config_sntp time-server-4="
  "ntp-update-time;           /etc/config-tools/get_ntp_config update-time;                     /etc/config-tools/config_sntp update-time="
  "ntp-state;                 /etc/config-tools/get_ntp_config state;                           /etc/config-tools/config_sntp state="

  "service-interface-owner;   /etc/config-tools/get_service_interface_config mode -b;           /etc/config-tools/config_service_interface mode="
  "rs232Owner;                /etc/config-tools/get_coupler_details RS232-owner;                /etc/config-tools/config_RS232 owner="
  "codesys-webserver-state;   /etc/config-tools/get_runtime_config cfg-version=2 webserver-state; /etc/config-tools/config_runtime cfg-version=2 webserver-state="
  "codesys3-webserver-state;  /etc/config-tools/get_runtime_config cfg-version=3 webserver-state; /etc/config-tools/config_runtime cfg-version=3 webserver-state="
  "ftp-state;                 /etc/config-tools/config_ssl ftp-status;                          /etc/config-tools/config_port port=ftp state="
  "ftps-state;                /etc/config-tools/config_ssl ftps-status;                         /etc/config-tools/config_port port=ftps state="
  "codesys-port-state;        /etc/config-tools/get_runtime_config service-state;               /etc/config-tools/config_runtime cfg-version=2 service-state="
  "codesys-port-number;       /etc/config-tools/get_runtime_config comm-port;                   /etc/config-tools/config_runtime cfg-version=2 comm-port="

  "ssh-state;                 /etc/config-tools/get_ssh_config state;                           /etc/config-tools/config_ssh state="
  "ssh-port-nr;               /etc/config-tools/get_ssh_config port-number;                     /etc/config-tools/config_ssh port-number="
  "ssh-root-login;            /etc/config-tools/get_ssh_config root-access-state;               /etc/config-tools/config_ssh root-access-state="
  "ssh-pwd-login;             /etc/config-tools/get_ssh_config password-request-state;          /etc/config-tools/config_ssh password-request-state="

  "http-state;                /etc/config-tools/config_ssl http-status;                         /etc/config-tools/config_port port=http  state="
  "https-state;               /etc/config-tools/config_ssl https-status;                        /etc/config-tools/config_port port=https state="
  "https-cipher-list;         /etc/config-tools/get_https_tls_config cipher-list;               /etc/config-tools/config_https_tls cipher-list="

  "tftp-state;                /etc/config-tools/get_tftp_config state;                          /etc/config-tools/config_tftp state="
  "tftp-dl-dir;               /etc/config-tools/get_tftp_config download-dir;                   /etc/config-tools/config_tftp download-dir="

  "codesys-port-auth;         /etc/config-tools/get_rts3scfg_value PASSWORD USEPWD;             /etc/config-tools/config_runtime cfg-version=2 authentication="
  "codesys3-port-auth;        /etc/config-tools/get_runtime_config cfg-version=3 authentication; /etc/config-tools/config_runtime cfg-version=3 authentication="

  "opcua-state;               /etc/config-tools/config_opcua state;                             /etc/config-tools/config_opcua state="

  "default-webserver;         /etc/config-tools/get_coupler_details default-webserver;          /etc/config-tools/config_runtime default-webpage="
  "snmp-general-state;        /etc/config-tools/get_port_state snmp;                            /etc/config-tools/config_snmp set-snmp="
  "snmp-device-name;          /etc/config-tools/get_snmp_data device-name;                      /etc/config-tools/config_snmp device-name="
  "snmp-description;          /etc/config-tools/get_snmp_data description;                      /etc/config-tools/config_snmp description="
  "snmp-physical-location;    /etc/config-tools/get_snmp_data physical-location;                /etc/config-tools/config_snmp physical-location="
  "snmp-contact;              /etc/config-tools/get_snmp_data contact;                          /etc/config-tools/config_snmp contact="
  "snmp-objectid;             /etc/config-tools/get_snmp_data objectID;                         /etc/config-tools/config_snmp objectID="
  "snmp-v1-v2-state;          /etc/config-tools/get_snmp_data v1-v2c-state;                     /etc/config-tools/config_snmp v1-v2c-state="
  "snmp-v1-v2-community-name; /etc/config-tools/get_snmp_data v1-v2c-community-name;            /etc/config-tools/config_snmp v1-v2c-community-name="
#  "screensaver-state;         /etc/config-tools/get_rts3scfg_value SCREENSAVER state;           /etc/config-tools/change_rts_config area=SCREENSAVER state="
#  "screensaver-waittime;      /etc/config-tools/get_rts3scfg_value SCREENSAVER WaitTime;        /etc/config-tools/change_rts_config area=SCREENSAVER WaitTime="
#  "cleanmode-timeout;         /etc/config-tools/get_rts3scfg_value CLEANMODE Timeout;           /etc/config-tools/change_rts_config area=CLEANMODE Timeout="

  "clock-display-mode;        /etc/config-tools/get_clock_data display-mode;                    /etc/config-tools/config_clock_display_mode display-mode="
  "clock-tz-string;           /etc/config-tools/get_clock_data tz-string;                       /etc/config-tools/config_timezone tz-string="

  "modbus-tcp-state;          /etc/config-tools/modbus_config get tcp enabled;                 /etc/config-tools/modbus_config set tcp enabled "
  "modbus-udp-state;          /etc/config-tools/modbus_config get udp enabled;                 /etc/config-tools/modbus_config set udp enabled "
  "modbus-alt-watchdog-enabled; /etc/config-tools/modbus_config get alternative-watchdog enabled; /etc/config-tools/modbus_config set alternative-watchdog enabled "
  "modbus-alt-watchdog-timeout; /etc/config-tools/modbus_config get alternative-watchdog timeout; /etc/config-tools/modbus_config set alternative-watchdog timeout "
  "modbus-alt-watchdog-options; /etc/config-tools/modbus_config get alternative-watchdog options; /etc/config-tools/modbus_config set alternative-watchdog options "

  "profibus-dp-ssa-user;      /etc/config-tools/pbdp_config get ssa.user ssa_released;          /etc/config-tools/pbdp_config set ssa.user ssa_released "
  
  "iocheck-port;              /etc/config-tools/get_iocheckport_config state;                   /etc/config-tools/config_iocheckport state="
  
  "sim-pin;                   /etc/config-tools/settings_backup_mdmd backup sim-pin;            /etc/config-tools/settings_backup_mdmd restore sim-pin "
  "port-enabled;              /etc/config-tools/settings_backup_mdmd backup port-enabled;       /etc/config-tools/settings_backup_mdmd restore port-enabled "
  "log-level;                 /etc/config-tools/settings_backup_mdmd backup log-level;          /etc/config-tools/settings_backup_mdmd restore log-level "

  "gprs-auth-type;            /etc/config-tools/settings_backup_mdmd backup gprs-auth-type;     /etc/config-tools/settings_backup_mdmd restore dummy "
  "gprs-username;             /etc/config-tools/settings_backup_mdmd backup gprs-username;      /etc/config-tools/settings_backup_mdmd restore dummy " 
  "gprs-apn;                  /etc/config-tools/settings_backup_mdmd backup gprs-apn;           /etc/config-tools/settings_backup_mdmd restore dummy "
  "gprs-connectivity;         /etc/config-tools/settings_backup_mdmd backup gprs-connectivity;  /etc/config-tools/settings_backup_mdmd restore gprs-connectivity "
  "net-selection;             /etc/config-tools/settings_backup_mdmd backup net-selection;      /etc/config-tools/settings_backup_mdmd restore net-selection " 
  
# backlight
  "backlight-backlighton;       /etc/config-tools/get_backlight backlighton;                    /etc/config-tools/config_backlight backlighton="
  "backlight-backlightoff;      /etc/config-tools/get_backlight backlightoff;                   /etc/config-tools/config_backlight backlightoff="
  "backlight-backlightonnight;  /etc/config-tools/get_backlight backlightonnight;               /etc/config-tools/config_backlight backlightonnight="
  "backlight-backlightoffnight; /etc/config-tools/get_backlight backlightoffnight;              /etc/config-tools/config_backlight backlightoffnight="
  "backlight-daynightswitch;    /etc/config-tools/get_backlight daynightswitch;                 /etc/config-tools/config_backlight daynightswitch="
  "backlight-nighttime;         /etc/config-tools/get_backlight nighttime;                      /etc/config-tools/config_backlight nighttime="
  "backlight-daytime;           /etc/config-tools/get_backlight daytime;                        /etc/config-tools/config_backlight daytime="
  "backlight-mastermode;        /etc/config-tools/get_backlight mastermode;                     /etc/config-tools/config_backlight mastermode="
  "backlight-usesensor;         /etc/config-tools/get_backlight usesensor;                      /etc/config-tools/config_backlight usesensor="
  "backlight-sensorranges;      /etc/config-tools/get_backlight sensorranges;                   /etc/config-tools/config_backlight sensorranges="
  "backlight-plusminusstep;     /etc/config-tools/get_backlight plusminusstep;                  /etc/config-tools/config_backlight plusminusstep="
  "backlight-testbacklight;     /etc/config-tools/get_backlight testbacklight;                  /etc/config-tools/config_backlight testbacklight="
# boot
  "boot-countdown;            /etc/config-tools/get_boot countdown;                             /etc/config-tools/config_boot countdown="
# configured
  "config-configured;         /etc/config-tools/get_configured configured;                      /etc/config-tools/config_configured configured="
# display  
  "display-orientation;       /etc/config-tools/get_display orientation;                        /etc/config-tools/config_display orientation="
  "display-care;              /etc/config-tools/get_display care;                               /etc/config-tools/config_display care="
  "display-caretime;          /etc/config-tools/get_display caretime;                           /etc/config-tools/config_display caretime="
  "display-calibonboot;       /etc/config-tools/get_display calibonboot;                        /etc/config-tools/config_display calibonboot="
  "display-calibtimeout;      /etc/config-tools/get_display calibtimeout;                       /etc/config-tools/config_display calibtimeout="
  "display-cleaningtimeout;   /etc/config-tools/get_display cleaningtimeout;                    /etc/config-tools/config_display cleaningtimeout="
# browser security
  "browsersecurity-level;     /etc/config-tools/get_browsersecurity level;                      /etc/config-tools/config_browsersecurity level="  
# gesture
  "gesture-state;             /etc/config-tools/get_gesture state;                              /etc/config-tools/config_gesture state="
  "gesture-scroll;            /etc/config-tools/get_gesture scroll;                             /etc/config-tools/config_gesture scroll="
  "gesture-menu;              /etc/config-tools/get_gesture menu;                               /etc/config-tools/config_gesture menu="
# motion sensor
  "motion-state;              /etc/config-tools/get_motionsensor state;                         /etc/config-tools/config_motionsensor state="
  "motion-direction;          /etc/config-tools/get_motionsensor direction;                     /etc/config-tools/config_motionsensor direction="
# plcselect
  "plcselect-reconnect;       /etc/config-tools/get_plcselect reconnect_interval;               /etc/config-tools/config_plcselect reconnect_interval="
  "plcselect-statemonitor;    /etc/config-tools/get_plcselect statemonitor;                     /etc/config-tools/config_plcselect statemonitor="
  "plcselect-plc_selected;    /etc/config-tools/get_plcselect plc_selected;                     /etc/config-tools/config_plcselect plc_selected="
# plcselect index 0
  "plcselect-url-0;           /etc/config-tools/get_plcselect 0 url;                            /etc/config-tools/config_plcselect 0 url="
  "plcselect-txt-0;           /etc/config-tools/get_plcselect 0 txt;                            /etc/config-tools/config_plcselect 0 txt="
  "plcselect-vkb-0;           /etc/config-tools/get_plcselect 0 vkb;                            /etc/config-tools/config_plcselect 0 vkb="
  "plcselect-mon-0;           /etc/config-tools/get_plcselect 0 mon;                            /etc/config-tools/config_plcselect 0 mon="
# plcselect index 1
  "plcselect-url-1;           /etc/config-tools/get_plcselect 1 url;                            /etc/config-tools/config_plcselect 1 url="
  "plcselect-txt-1;           /etc/config-tools/get_plcselect 1 txt;                            /etc/config-tools/config_plcselect 1 txt="
  "plcselect-vkb-1;           /etc/config-tools/get_plcselect 1 vkb;                            /etc/config-tools/config_plcselect 1 vkb="
  "plcselect-mon-1;           /etc/config-tools/get_plcselect 1 mon;                            /etc/config-tools/config_plcselect 1 mon="
# plcselect index 2
  "plcselect-url-2;           /etc/config-tools/get_plcselect 2 url;                            /etc/config-tools/config_plcselect 2 url="
  "plcselect-txt-2;           /etc/config-tools/get_plcselect 2 txt;                            /etc/config-tools/config_plcselect 2 txt="
  "plcselect-vkb-2;           /etc/config-tools/get_plcselect 2 vkb;                            /etc/config-tools/config_plcselect 2 vkb="
  "plcselect-mon-2;           /etc/config-tools/get_plcselect 2 mon;                            /etc/config-tools/config_plcselect 2 mon="
# plcselect index 3
  "plcselect-url-3;           /etc/config-tools/get_plcselect 3 url;                            /etc/config-tools/config_plcselect 3 url="
  "plcselect-txt-3;           /etc/config-tools/get_plcselect 3 txt;                            /etc/config-tools/config_plcselect 3 txt="
  "plcselect-vkb-3;           /etc/config-tools/get_plcselect 3 vkb;                            /etc/config-tools/config_plcselect 3 vkb="
  "plcselect-mon-3;           /etc/config-tools/get_plcselect 3 mon;                            /etc/config-tools/config_plcselect 3 mon="
# plcselect index 4
  "plcselect-url-4;           /etc/config-tools/get_plcselect 4 url;                            /etc/config-tools/config_plcselect 4 url="
  "plcselect-txt-4;           /etc/config-tools/get_plcselect 4 txt;                            /etc/config-tools/config_plcselect 4 txt="
  "plcselect-vkb-4;           /etc/config-tools/get_plcselect 4 vkb;                            /etc/config-tools/config_plcselect 4 vkb="
  "plcselect-mon-4;           /etc/config-tools/get_plcselect 4 mon;                            /etc/config-tools/config_plcselect 4 mon="
# plcselect index 5
  "plcselect-url-5;           /etc/config-tools/get_plcselect 5 url;                            /etc/config-tools/config_plcselect 5 url="
  "plcselect-txt-5;           /etc/config-tools/get_plcselect 5 txt;                            /etc/config-tools/config_plcselect 5 txt="
  "plcselect-vkb-5;           /etc/config-tools/get_plcselect 5 vkb;                            /etc/config-tools/config_plcselect 5 vkb="  
  "plcselect-mon-5;           /etc/config-tools/get_plcselect 5 mon;                            /etc/config-tools/config_plcselect 5 mon="
# plcselect index 6
  "plcselect-url-6;           /etc/config-tools/get_plcselect 6 url;                            /etc/config-tools/config_plcselect 6 url="
  "plcselect-txt-6;           /etc/config-tools/get_plcselect 6 txt;                            /etc/config-tools/config_plcselect 6 txt="
  "plcselect-vkb-6;           /etc/config-tools/get_plcselect 6 vkb;                            /etc/config-tools/config_plcselect 6 vkb="
  "plcselect-mon-6;           /etc/config-tools/get_plcselect 6 mon;                            /etc/config-tools/config_plcselect 6 mon="
# plcselect index 7
  "plcselect-url-7;           /etc/config-tools/get_plcselect 7 url;                            /etc/config-tools/config_plcselect 7 url="
  "plcselect-txt-7;           /etc/config-tools/get_plcselect 7 txt;                            /etc/config-tools/config_plcselect 7 txt="
  "plcselect-vkb-7;           /etc/config-tools/get_plcselect 7 vkb;                            /etc/config-tools/config_plcselect 7 vkb="
  "plcselect-mon-7;           /etc/config-tools/get_plcselect 7 mon;                            /etc/config-tools/config_plcselect 7 mon="
# plcselect index 8
  "plcselect-url-8;           /etc/config-tools/get_plcselect 8 url;                            /etc/config-tools/config_plcselect 8 url="
  "plcselect-txt-8;           /etc/config-tools/get_plcselect 8 txt;                            /etc/config-tools/config_plcselect 8 txt="
  "plcselect-vkb-8;           /etc/config-tools/get_plcselect 8 vkb;                            /etc/config-tools/config_plcselect 8 vkb="
  "plcselect-mon-8;           /etc/config-tools/get_plcselect 8 mon;                            /etc/config-tools/config_plcselect 8 mon="
# plcselect index 9
  "plcselect-url-9;           /etc/config-tools/get_plcselect 9 url;                            /etc/config-tools/config_plcselect 9 url="
  "plcselect-txt-9;           /etc/config-tools/get_plcselect 9 txt;                            /etc/config-tools/config_plcselect 9 txt="
  "plcselect-vkb-9;           /etc/config-tools/get_plcselect 9 vkb;                            /etc/config-tools/config_plcselect 9 vkb="
  "plcselect-mon-9;           /etc/config-tools/get_plcselect 9 mon;                            /etc/config-tools/config_plcselect 9 mon="
# plcselect index 10
  "plcselect-url-10;          /etc/config-tools/get_plcselect 10 url;                           /etc/config-tools/config_plcselect 10 url="
  "plcselect-txt-10;          /etc/config-tools/get_plcselect 10 txt;                           /etc/config-tools/config_plcselect 10 txt="
  "plcselect-vkb-10;          /etc/config-tools/get_plcselect 10 vkb;                           /etc/config-tools/config_plcselect 10 vkb="
  "plcselect-mon-10;          /etc/config-tools/get_plcselect 10 mon;                           /etc/config-tools/config_plcselect 10 mon="
# plcselect index 11
  "plcselect-url-11;           /etc/config-tools/get_plcselect 11 url;                          /etc/config-tools/config_plcselect 11 url="
  "plcselect-txt-11;           /etc/config-tools/get_plcselect 11 txt;                          /etc/config-tools/config_plcselect 11 txt="
  "plcselect-vkb-11;           /etc/config-tools/get_plcselect 11 vkb;                          /etc/config-tools/config_plcselect 11 vkb="
  "plcselect-mon-11;           /etc/config-tools/get_plcselect 11 mon;                          /etc/config-tools/config_plcselect 11 mon="
# screensaver
  "screensaver-state;         /etc/config-tools/get_screensaver state;                          /etc/config-tools/config_screensaver state="
  "screensaver-mode;          /etc/config-tools/get_screensaver mode;                           /etc/config-tools/config_screensaver mode="
  "screensaver-theme;         /etc/config-tools/get_screensaver theme;                          /etc/config-tools/config_screensaver theme="
  "screensaver-image;         /etc/config-tools/get_screensaver image;                          /etc/config-tools/config_screensaver image="
  "screensaver-text;          /etc/config-tools/get_screensaver text;                           /etc/config-tools/config_screensaver text="
  "screensaver-time;          /etc/config-tools/get_screensaver time;                           /etc/config-tools/config_screensaver time="
# touchbeeper
  "touchbeeper-state;         /etc/config-tools/get_touchbeeper state;                          /etc/config-tools/config_touchbeeper state="
  "touchbeeper-duration;      /etc/config-tools/get_touchbeeper duration;                       /etc/config-tools/config_touchbeeper duration="
# pointercal
  "touch-calibration;         /etc/config-tools/get_pointercal;                                 /etc/config-tools/config_pointercal "
  )


#FIXME: reimplement properly instead of parsing XML file
GetPortsList ()
{
    /usr/bin/xmlstarlet sel -t -m //ip_settings/port_name -v . -o " " /etc/specific/network-interfaces.xml
}


# Function to process of an error after restory operation.
#
# If returned value of the last restore operation is not SUCCESS, then error text, 
# name of erroneous parameter and last error text (if it is found) will be logged 
# and global error counter will be incremented. 
#
# Param 1: returned value of last restore operation 
# Param 2: error text
# Param 3: name of erroneous parameter 
#
# Return: 0 (success)
#-----------------------------------------------------------------------------#
ProcessErrRestoreOperation ()
{
  local errorCode=$1
  local errorText="$2"
  local errorParam="$3"
  local lastError=""
  if [[ "$errorCode" != "$SUCCESS" ]]; then
     if [[ -f "$LAST_ERROR_FILENAME" ]]; then
     	 read lastError < "$LAST_ERROR_FILENAME"
     fi
     if [ -n "$lastError" ]; then
     		ReportError $errorCode "$errorText  \"$errorParam\" \"$lastError\""
     else
     	  ReportError $errorCode "$errorText  \"$errorParam\""
     fi	  
     restore_error_count=$((restore_error_count+1))
  fi
  return 0
}

# Function to process of an error after backup operation.
#
# If returned value of the last backup operation is not SUCCESS, then error text, 
# name of erroneous parameter and last error text (if it is found) will be logged 
# and global error counter will be incremented. 
#
# Param 1: returned value of last restore operation 
# Param 2: error text
# Param 3: name of erroneous parameter 
#
# Return: 0 (succsess)
#-----------------------------------------------------------------------------#
ProcessErrBackupOperation ()
{
  local errorCode=$1
  local errorText="$2"
  local errorParam="$3"
  local lastError=""
  
  if [[ "$errorCode" != "$SUCCESS" ]]; then 
     if [[ -f "$LAST_ERROR_FILENAME" ]]; then
     		read lastError < "$LAST_ERROR_FILENAME"
     fi
     if [ -n "$lastError" ]; then
     		ReportError $errorCode "$errorText  \"$errorParam\" \"$lastError\""
     else
     	  ReportError $errorCode "$errorText  \"$errorParam\""
     fi	 
     backup_error_count=$((backup_error_count+1))
  fi
  return 0
}

