#!/bin/bash
#-----------------------------------------------------------------------------#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# This file is part of project fwupdate (PTXdist package rauc_bundle_conf).
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#
#-----------------------------------------------------------------------------#
# Script:   hooks_common
#
# Brief:    WAGO firmware update RAUC hook common defines and functions.
#
# Author:   PEn: WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#


# General hook defines
readonly WAGO_FW_UPDATE_SETTINGS_BACKUP_ASYNC=0
readonly WAGO_FW_UPDATE_SETTINGS_LOCK_FD=201
readonly WAGO_FW_UPDATE_SETTINGS_LOCK="/var/lock/fwupdate-settings.lock"
readonly WAGO_FW_UPDATE_SETTINGS_COMPLETION_TIMEOUT=300


# Load firmware update definitions and functions.
readonly WAGO_ST_DIR="/usr/sbin"
if [ ! -f "$WAGO_ST_DIR/fwupdate_common" ]; then
    echo "Missing dependency fwupdate_common"
    exit 64
fi
source "$WAGO_ST_DIR/fwupdate_common"
