#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

# Update network configuration possibly provided by dhcp.

DHCP_DATA_FILE=/tmp/dhcp-bootp-data-$IFACE
EVENTDIR=/etc/config-tools/events/networking

rm -f $DHCP_DATA_FILE
[ -e $EVENTDIR ] && run-parts -a config $EVENTDIR
