#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#
# finalize_root
#

# finalize_root sets the current NAND/EMMC root partition as default.
# It is important after a firmware update, when the system starts from
# the newly updated root partition for the first time.

# When running from SD card, the script shall do nothing.

# It should be called late during the bootup.

GET_FS_DATA=/etc/config-tools/get_filesystem_data
RAUC=/usr/sbin/rauc_failsafe.sh

if [[ ! -x "$GET_FS_DATA" ]]; then
  echo "Error: $GET_FS_DATA is no executable."
  exit 1
fi

if ! [[ "$($GET_FS_DATA active-partition-medium)" =~ internal-flash-.* ]]; then
  #echo "$0: DEBUG: root partition is not flash - do nothing."
  exit 0
fi

case $1 in

  start)
    [ -x ${RAUC} ] &&
      ${RAUC} status mark-good > /dev/null &&
      ${RAUC} status mark-active > /dev/null
    if [[ $? -ne 0 ]]; then
      echo "Error: Failed to mark the active system as good!"
    fi
  ;;
  stop)
  ;;
esac
