#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2020 WAGO Kontakttechnik GmbH & Co. KG

#-----------------------------------------------------------------------------#
# Script-name: update_config
#
# Updates networking configuration of hostname and dns domainname.
# Typically called when configuration data changed by config tools or by
# DHCP/BOOTP.
#
# $Revision$
# Author: WAGO Kontakttechnik GmbH & Co. KG.
#-----------------------------------------------------------------------------#

set -u      # error exit on undefined shell variables


function DomainToResolvConf()
{
    local validdomain=$1
    local resolvconf=/etc/resolv.conf

    if [ "$validdomain" ]; then
        if [ -s $resolvconf ]; then
            # resolv.conf not empty, can use sed, insert search line
            sed -i -e "1isearch $validdomain" -e "/^search/d" $resolvconf
        else
            # no sed on empty file
            echo "search $validdomain" > $resolvconf
        fi
    else
        # empty domain name, remove any search line in resolv.conf
        sed -i -e "/^search/d" $resolvconf
    fi
}

#Writing the domain to dnsmasq_default configuration file.
#The file /etc/dnsmasq.conf can't be used because it is
#rewritten on every dnsmasq configuration change from WBM/CBM.
function DomainToDNSMASQ()
{
    local domain=$1
    local dnsmasq_conf=/etc/dnsmasq.d/dnsmasq_default.conf

    #get actual domain
    local act_domain=""
    IFS="=" read -r dummy act_domain <<< "$(grep -E '^domain=' $dnsmasq_conf)"

    if [ "$act_domain" != "$domain" ]; then
        if [ "$domain" ]; then
            #check if act_domain differs from new_domain
            local domain_search="/^\(#\)\?domain=.*"
            
            #search for the first '#domain=' or 'domain=' at the beginning of the line
            #replace it with 'domain=$domain'
            sed -i -e "1,$domain_search/{$domain_search/s//domain=$domain/}" $dnsmasq_conf
        else
            #no domain -> we have to comment the domain-parameter (#domain=)
            #otherwise dmasq will fail during startup
            sed -i -e "/^domain=/c#domain=" $dnsmasq_conf
        fi
        #now we have to restart dnsmasq there is no other way to re-read the configuration.
        /etc/init.d/dnsmasq restart
    fi
}

function UpdateLocalDNSResolve()
{
   local hostname=$1
   local FQDN="$hostname.$2"

   local ips=$(ip addr ls | grep inet.*global | awk '{ print $2}' | sed 's+/.*++g')

   local marker_text_1="#SYSTEM HOST ENTRY -- DO NOT REMOVE -- WILL BE CREATED BY CONFIG-TOOLS"
   local marker_text_2="#END SYSTEM HOST -- DO NOT REMOVE"

   # create Marker if not present
   grep -q "^$marker_text_1" /etc/hosts || echo "$marker_text_1" >> /etc/hosts
   grep -q "^$marker_text_2" /etc/hosts || echo "$marker_text_2" >> /etc/hosts

   #remove everything between marker1 and marker2
   sed -i -e "/$marker_text_1/,/$marker_text_2/{/$marker_text_1/b;/$marker_text_2/b;d}" /etc/hosts

   for ip in $ips; do
     sed -i -e "/^$marker_text_1/a$ip\t$FQDN\t$hostname" /etc/hosts
   done

}

function UpdateHostConf()
{
    local validhost
    local validdomain
    local defaulthost

    # set default hostname
    defaulthost=$(/etc/config-tools/determine_hostname --default)
    grep -q "^127\.0\.1\.1" /etc/hosts || sed -i -e "/^127\.0\.0\.1/a127.0.1.1\t$defaulthost\t$defaulthost" /etc/hosts

    # load static names
    . "$HOSTCONFFILE"
    [ "$HOSTNAME" ] && validhost=$HOSTNAME
    [ "$DNSDOMAIN" ] && validdomain=$DNSDOMAIN

    # now load dynamic dhcp names of newest file
    if [ "$(find /tmp -name "dhcp-bootp-data-"* -type f -printf . | wc -c)" -gt 0 ]; then
        cfgfile=$(ls -rt "$DHCP_DATA_FILE_TEMPLATE"* | tail -1)
        DHCPHOSTNAME=
        DHCPDOMAIN=
        . "$cfgfile"
        [ "$DHCPHOSTNAME" ] && validhost=$DHCPHOSTNAME
        [ "$DHCPDOMAIN" ] && validdomain=$DHCPDOMAIN
    fi

    if [ "${validhost-}" != "$(</proc/sys/kernel/hostname)" ] || [ "${validdomain-}" != "$(dnsdomainname)" ]; then
        # write /etc/hosts, set /etc/hostname, and kernel hostname
        if [ "${validhost-}" ]; then
            if [ "${validdomain-}" ]; then
                FQDN=$validhost.$validdomain
            else
                FQDN=$validhost
            fi
            if grep -q "^127.0.1.1" /etc/hosts; then
                sed -i -e "/^127\.0\.1\.1/c127.0.1.1\t$FQDN\t$validhost" /etc/hosts
            else
                echo -e "127.0.1.1\t$FQDN\t$validhost" >> /etc/hosts
            fi
            echo "$validhost" > /etc/hostname
            echo "$validhost" > /proc/sys/kernel/hostname
        else
            # empty hostname, clear hostname files and set default hostname in kernel
            if [ "${validdomain-}" ]; then
                sed -i -e "/^127\.0\.1\.1/c127.0.1.1\t$defaulthost.$validdomain\t$defaulthost" /etc/hosts
            else
                sed -i -e "/^127\.0\.1\.1/c127.0.1.1\t$defaulthost\t$defaulthost" /etc/hosts
            fi
            rm -f /etc/hostname
            echo "$defaulthost" > /proc/sys/kernel/hostname
        fi
        DomainToResolvConf "${validdomain-}"
        if [ "${validhost-}" ]; then
            UpdateLocalDNSResolve "$validhost" "$validdomain"
        else
            UpdateLocalDNSResolve "$defaulthost" "$validdomain"
        fi
        DomainToDNSMASQ "${validdomain-}"
    fi
}

function UpdateDnsmasqConfig()
{
    DNSMASQ_CONFIG="/etc/dnsmasq.conf"
    DNSMASQ_CONFIG_TMP="/tmp/dnsmasq.conf"

    /etc/config-tools/config_dnsmasq_c --gen-config --dnsmasq-config $DNSMASQ_CONFIG_TMP

    if ! diff -q $DNSMASQ_CONFIG $DNSMASQ_CONFIG_TMP ; then
        # During restart a new dnsmasq configuration is generated.
        /etc/init.d/dnsmasq restart
    fi

    rm -f $DNSMASQ_CONFIG_TMP &> /dev/null
}

function DoUpdates()
{
    UpdateHostConf
}

# main: set global variables
PATH="/bin:/sbin:/usr/bin:/usr/sbin"
DHCP_DATA_FILE_PREFIX=dhcp-bootp-data-
DHCP_DATA_FILE_TEMPLATE=/tmp/$DHCP_DATA_FILE_PREFIX
HOSTCONFFILE=/etc/specific/host.conf

# Use advisory lock to avoid race with config_dnsmasq_c and this script on more then one 
# interface with dhcp
( flock 9; DoUpdates; ) 9< /etc/hosts
sync

# dnsmasq update relies on /etc/hosts too. Therefore, run dnsmasq update after DoUpdates part. 
UpdateDnsmasqConfig
