#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG

set -u

ROUTING_CONFIG_FILE="/etc/specific/routing.conf"
ROUTING_CONFIG_TMP_FILE="/etc/specific/routing.conf.tmp"
ROUTING_CONFIG_PREFIX="routing"
MOVE="/bin/mv"

# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
    print_dbg "config_tool_lib missing"
    exit 255
fi

. "/etc/config-tools/config_tool_lib"


function PrintUsage
{
    echo "backup_routing --save <backup-file>      backup routing parameters"
    echo "backup_routing --restore <backup-file>   restore routing parameters"
    echo "backup_routing --param-count             get number of routing parameters to save"
}


# Write logging data using syslog.
#
# Input: Message to log.
#
function Log
{
    [[ $# > 0 ]] && logger -t "backup-routing" "$1"
}


# Read routing configuration data from routing configuration file.
#
# Output: returns config tool status, see /etc/config-tools/config_tool_defines.
#
function ReadConfigFile
{
    local status=$SUCCESS
    
    if [[ -e $ROUTING_CONFIG_FILE ]]; then
        . $ROUTING_CONFIG_FILE
    else
        status=$CONFIG_FILE_MISSING
        Log "Could not read \"$ROUTING_CONFIG_FILE\""
    fi
    
    return $status
}


# Write routing configuration to routing configuration file.
#
# The data to write is taken from arrays 
#  - static routing  (static_<*>)
#  - masquerading    (masquerading_<*>)
#  - port forwarding (port_forwarding_<*>)
#
# Output: returns config tool status, see /etc/config-tools/config_tool_defines.
#
function WriteConfigFile
{
    # Write temporary file first. After write operation is completed move temporary file to routing config file.
    local count
    local index
    local status=$SUCCESS

    # Write general routing parameters
    if [[ "${state-}" ]]; then
        echo "state=$state" > $ROUTING_CONFIG_TMP_FILE

        # Write static route parameters
        if [[ $(IsValidStaticRouteEntries) == "true" ]]; then
            index=0
            count=0
            [[ -n "${static_dest[@]-}" ]] && count="${#static_dest[@]}"
            [[ $count -gt 0 ]] && echo >> $ROUTING_CONFIG_TMP_FILE
            while [[ $index -lt $count ]]; do
                echo "static_dest[$index]=${static_dest[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                echo "static_dest_mask[$index]=${static_dest_mask[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                echo "static_gw[$index]=${static_gw[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                echo "static_metric[$index]=${static_metric[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                echo "static_routing_type[$index]=${static_routing_type[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                echo "static_state[$index]=${static_state[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                ((index++))
            done
        else
            Log "Invalid static route entries found."
        fi

        # Write masquerading parameters
        if [[ $(IsValidMasquerading) == "true" ]]; then
            index=0
            count=0
            [[ -n "${masquerading_interface[@]-}" ]] && count="${#masquerading_interface[@]}"
            [[ $count -gt 0 ]] && echo >> $ROUTING_CONFIG_TMP_FILE
            while [[ $index -lt $count ]]; do
                echo "masquerading_interface[$index]=${masquerading_interface[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                echo "masquerading_state[$index]=${masquerading_state[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                echo "masquerading_routing_type[$index]=${masquerading_routing_type[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                ((index++))
            done
        else
            Log "Invalid masquerading entries found."
        fi

        # Write port-forwarding parameters
        if [[ $(IsValidPortForwarding) == "true" ]]; then
            index=0
            count=0
            [[ -n "${port_forwarding_interface[@]-}" ]] && count="${#port_forwarding_interface[@]}"
            [[ $count -gt 0 ]] && echo >> $ROUTING_CONFIG_TMP_FILE
            while [[ $index -lt $count ]]; do
                echo "port_forwarding_interface[$index]=${port_forwarding_interface[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                echo "port_forwarding_state[$index]=${port_forwarding_state[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                echo "port_forwarding_port[$index]=${port_forwarding_port[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                echo "port_forwarding_protocol[$index]=${port_forwarding_protocol[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                echo "port_forwarding_forward_ip[$index]=${port_forwarding_forward_ip[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                echo "port_forwarding_forward_port[$index]=${port_forwarding_forward_port[$index]}" >> $ROUTING_CONFIG_TMP_FILE
                ((index++))
            done
        else
            Log "Invalid port forwarding entries found."
        fi
    else
        Log "$0: Inconsistent routing configuration backup file. General routing state parameter missing."
        status=$CONFIG_FILE_INCONSISTENT
    fi
    sync
    $MOVE $ROUTING_CONFIG_TMP_FILE $ROUTING_CONFIG_FILE
    
    return $status
}


# Check if all arrays representing the static route configuration are defined and equal sized.
#
# Output: true,  in case all arrays are defined and have same element count or all arrays are undefined, representing an element count of zero.
#         false, in case array sizes differ or only part of arrays are undefined
#
function IsValidStaticRouteEntries
{
    if [[ "${static_dest_mask-}" && "${static_gw-}" && "${static_metric-}" && "${static_routing_type-}" && "${static_state-}" ]]; then
         
        local count=${#static_dest[@]}
        if [[   ${#static_dest_mask[@]} == $count
             && ${#static_gw[@]} == $count
             && ${#static_metric[@]} == $count
             && ${#static_routing_type[@]} == $count
             && ${#static_state[@]} == $count ]]; then
            echo "true"
        else
            echo "false"
        fi
    else
        if [[ "${static_dest_mask-}" || "${static_gw-}" || "${static_metric-}" || "${static_routing_type-}" || "${static_state-}" ]]; then
            echo "false"
        else
            # All entries are zero; no static routes were specified.
            echo "true"
        fi
    fi
}


# Append static route configuration to backup file.
#
# Output: returns config tool status, see /etc/config-tools/config_tool_defines.
#
function PrintStaticRouteEntries
{
    local count=0
    local index=0
    local status=$SUCCESS
    local file=$1
    
    [[ -n "${static_dest[@]-}" ]] && count="${#static_dest[@]}"
    [[ $(IsValidStaticRouteEntries) == "false" ]] && status=$CONFIG_FILE_INCONSISTENT

    if [[ $status == $SUCCESS ]]; then
        while [[ $index -lt $count ]]; do
            echo "${ROUTING_CONFIG_PREFIX}-static-dest=$index|${static_dest[$index]}" >> $file
            echo "${ROUTING_CONFIG_PREFIX}-static-dest-mask=$index|${static_dest_mask[$index]}" >> $file
            echo "${ROUTING_CONFIG_PREFIX}-static-gw=$index|${static_gw[$index]}" >> $file
            echo "${ROUTING_CONFIG_PREFIX}-static-metric=$index|${static_metric[$index]}" >> $file
            echo "${ROUTING_CONFIG_PREFIX}-static-routing-type=$index|${static_routing_type[$index]}" >> $file
            echo "${ROUTING_CONFIG_PREFIX}-static-state=$index|${static_state[$index]}" >> $file
            ((index++))
        done
    fi
    
    return $status
}


# Check if all arrays representing the masquerading configuration are defined and equal sized.
#
# Output: true,  in case all arrays are defined and have same element count or all arrays are undefined, representing an element count of zero.
#         false, in case array sizes differ or only part of arrays are undefined
#
function IsValidMasquerading
{
    if [[ "${masquerading_interface-}" && "${masquerading_state-}" && "${masquerading_routing_type-}" ]]; then
        local count=${#masquerading_interface[@]}
        if [[    ${#masquerading_state[@]} == $count
              && ${#masquerading_routing_type[@]} == $count ]]; then
            echo "true"
        else
            echo "false"
        fi
    else
        if [[ "${masquerading_interface-}" || "${masquerading_state-}" || "${masquerading_routing_type-}" ]]; then
            echo "false"
        else
            # All entries are zero; no masquerading entries were specified.
            echo "true"
        fi
    fi
}


# Append masquerading configuration to backup file.
#
# Output: returns config tool status, see /etc/config-tools/config_tool_defines.
#
function PrintMasqueradingEntries
{
    local count=0
    local index=0
    local status=$SUCCESS
    local file=$1

    # Ensure all arrays have the same element count.
    [[ -n "${masquerading_interface[@]-}" ]] && count=${#masquerading_interface[@]}
    [[ $(IsValidMasquerading) == "false" ]] && status=$CONFIG_FILE_INCONSISTENT

    if [[ $status == $SUCCESS ]]; then
        while [[ $index -lt $count ]]; do
            echo "${ROUTING_CONFIG_PREFIX}-masquerading-interface=$index|${masquerading_interface[$index]}" >> $file
            echo "${ROUTING_CONFIG_PREFIX}-masquerading-state=$index|${masquerading_state[$index]}" >> $file
            echo "${ROUTING_CONFIG_PREFIX}-masquerading-routing-type=$index|${masquerading_routing_type[$index]}" >> $file
            ((index++))
        done
    fi
    
    return $status
}


# Check if all arrays representing the port forwarding configuration are defined and equal sized.
#
# Output: true,  in case all arrays are defined and have same element count or all arrays are undefined, representing an element count of zero.
#         false, in case array sizes differ or only part of arrays are undefined
#
function IsValidPortForwarding
{
    if [[ "${port_forwarding_state-}" && "${port_forwarding_port-}" && "${port_forwarding_protocol-}" && "${port_forwarding_forward_ip-}" && "${port_forwarding_forward_port-}" ]]; then
        local count=${#port_forwarding_interface[@]}
        if [[    ${#port_forwarding_state[@]} == $count
              && ${#port_forwarding_port[@]} == $count
              && ${#port_forwarding_protocol[@]} == $count
              && ${#port_forwarding_forward_ip[@]} == $count
              && ${#port_forwarding_forward_port[@]} == $count ]]; then
            echo "true"
        else
            echo "false"
        fi
    else
        if [[ "${port_forwarding_state-}" || "${port_forwarding_port-}" || "${port_forwarding_protocol-}" || "${port_forwarding_forward_ip-}" || "${port_forwarding_forward_port-}" ]]; then
            echo "false"
        else
            # All entries are zero; no port forwarding entries were specified.
            echo "true"
        fi
    fi
}


# Append port forwarding configuration to backup file.
#
# Output: returns config tool status, see /etc/config-tools/config_tool_defines.
#
function PrintPortForwardingEntries
{
    local count=0
    local index=0
    local status=$SUCCESS
    local file=$1
    
    [[ -n "${port_forwarding_interface[@]-}" ]] && count="${#port_forwarding_interface[@]}"
    [[ $(IsValidPortForwarding) == "false" ]] && status=$CONFIG_FILE_INCONSISTENT

    if [[ $status == $SUCCESS ]]; then
        while [[ $index -lt $count ]]; do
            echo "${ROUTING_CONFIG_PREFIX}-port-forwarding-interface=$index|${port_forwarding_interface[$index]}" >> $file
            echo "${ROUTING_CONFIG_PREFIX}-port-forwarding-state=$index|${port_forwarding_state[$index]}" >> $file
            echo "${ROUTING_CONFIG_PREFIX}-port-forwarding-port=$index|${port_forwarding_port[$index]}" >> $file
            echo "${ROUTING_CONFIG_PREFIX}-port-forwarding-protocol=$index|${port_forwarding_protocol[$index]}" >> $file
            echo "${ROUTING_CONFIG_PREFIX}-port-forwarding-forward-ip=$index|${port_forwarding_forward_ip[$index]}" >> $file
            echo "${ROUTING_CONFIG_PREFIX}-port-forwarding-forward-port=$index|${port_forwarding_forward_port[$index]}" >> $file
            ((index++))
        done
    fi
    
    return $status
}


#### Backup & Restore ##############################################################################

# Get number of parameters that have to be saved during backup.
#
# output: 1.) number of parameters to save during backup.
#         2.) returns config tool status, see /etc/config-tools/config_tool_defines.
#
function GetParameterCount
{
    local status
    local count=0
    
    # Subsequent variables and arrays might be set during ReadConfigFile call.
    declare state
    declare -a static_dest
    declare -a masquerading_interface
    declare -a port_forwarding_interface
    
    ReadConfigFile
    status=$?
    
    if [[ $status == $SUCCESS ]]; then
        # add 1 for general routing state
        [[ "${state-}" ]] && ((count++))
        # add array sizes
        [[ "${static_dest-}" ]] && (( count+=(${#static_dest[@]} * 6) ))
        [[ "${masquerading_interface-}" ]] && (( count+=(${#masquerading_interface[@]} * 3) ))
        [[ "${port_forwarding_interface-}" ]] && (( count+=(${#port_forwarding_interface[@]} * 6) ))
    fi
    
    echo $count
    return $status
}


# Save configuration parameters to backup file.
# 
# input:  backup file path
# output: returns config tool status, see /etc/config-tools/config_tool_defines.
#
function Save
{
    local status
    local file=$1
    
    # Subsequent variables and arrays might be set during ReadConfigFile call.
    declare state
    declare -a static_dest
    declare -a masquerading_interface
    declare -a port_forwarding_interface
    
    # Read config file: . "$CONFIG_FILE"
    ReadConfigFile
    status=$?
    
    # Write arrays to file, adding prefix.
    if [[ $status == $SUCCESS ]]; then
        if [[ "${state-}" ]]; then
            # general routing state
            echo "${ROUTING_CONFIG_PREFIX}-state=$state" >> $file
            # arrays
            [[ "${static_dest-}" ]] && (PrintStaticRouteEntries $file; status=$?)
            [[ "${masquerading_interface-}" && $status == $SUCCESS ]] && (PrintMasqueradingEntries $file; status=$?)
            [[ "${port_forwarding_interface-}" && $status == $SUCCESS ]] && (PrintPortForwardingEntries $file; status=$?)
        else
            Log "$0: Inconsistent routing configuration file. General routing state parameter missing."
            status=$CONFIG_FILE_INCONSISTENT
        fi
    fi
    
    return $status
}


# Restore configuration parameters from backup file.
# 
# input: backup file path
# output: returns config tool status, see /etc/config-tools/config_tool_defines.
#
function Restore
{
    local status=$SUCCESS
    local file=$1
    declare -a routing_params
    declare state
    
    # Subsequent variables and arrays might be set during file parse process.
    # Static route parameters
    declare -a static_dest
    declare -a static_dest_mask
    declare -a static_gw
    declare -a static_metric
    declare -a static_routing_type # Cannot be modified by user.
    declare -a static_state # read only

    # Masquerading parameters
    declare -a masquerading_interface
    declare -a masquerading_state
    declare -a masquerading_routing_type # Cannot be modified by user.

    # Port-Forwarding parameters
    declare -a port_forwarding_state
    declare -a port_forwarding_interface
    declare -a port_forwarding_port
    declare -a port_forwarding_protocol
    declare -a port_forwarding_forward_ip
    declare -a port_forwarding_forward_port
    
    
    # Get routing relevant data from file: grep for prefix
    # Store each line to array.
    if [[ $status == $SUCCESS ]]; then
        routing_params=($(grep ^$ROUTING_CONFIG_PREFIX $file))
        [[ -z "${routing_params-}" ]] && status=$CONFIG_FILE_INCONSISTENT
    fi
    
    if [[ $status == $SUCCESS ]]; then
        # TODO: Do we realy need to backup the internal field separator here?
        IFS_BKP=$IFS

        # Parse array entries
        for entry in ${routing_params[@]}; do
            IFS='=|' # reset internal field separator
            param=($entry)
            if [[ ${#param[@]} == 3 ]]; then
                name=${param[0]/${ROUTING_CONFIG_PREFIX}-/}
                # Initialize array element
                read "${name//-/_}[${param[1]}]" <<< ${param[2]}
                
            elif [[ ${#param[@]} == 2 ]]; then
                name=${param[0]/${ROUTING_CONFIG_PREFIX}-/}
                printf -v "${name//-/_}" "${param[1]}"
            fi
        done
        
        # Write configuration file.
        [[ $status == $SUCCESS ]] && WriteConfigFile
    fi
    
    return $status
}


#### MAIN ##########################################################################################

status=$SUCCESS

if [[ $# -ge 1 ]]; then
    operation=$1
    
    if [[ $# -ge 2 ]]; then
        file=$2
        if [[ "$operation" == "--save" ]]; then
            Save $file
            status=$?
        elif [[ "$operation" == "--restore" ]]; then
            Restore $file
            status=$?
        else
            # Unknown operation
            status=$INTERNAL_ERROR
            Log "$0: Unknown operation \"$operation\""
        fi
    else
        if [[ "$operation" == "--param-count" ]]; then
            GetParameterCount
        elif [[ "$operation" == "-h" || "$operation" == "--help" ]]; then
            PrintUsage
        else
            # Unknown operation
            status=$INTERNAL_ERROR
            Log "$0: Unknown or incomplete operation \"$operation\""
        fi
    fi
fi

exit $status
