#!/bin/bash
#-----------------------------------------------------------------------------#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2017-2022 WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#
#-----------------------------------------------------------------------------#
# Script:   /etc/config-tools/settings_factory
#
# Brief:    Restore settings to factory default, once stored into
#           /etc/config-tools/default-settings
#           on first controller boot with new installed firmware.
#           Also restore passwords and clean CODESYS runtime boot projects.
#
# Author:   HJH: WAGO GmbH & Co. KG
#-----------------------------------------------------------------------------#

DEFAULT_SETTINGS_DIR=/etc/config-tools/default-settings
DEFAULT_SETTINGS_FILENAME=default_settings

# show help-text if requested
if [ "$1" = "-h" -o "$1" = "--help" ]; then
    echo
    echo "* Handle controller factory settings *"
    echo
    echo "Usage: settings_factory [save]"
    echo
    echo "Restore factory defaults if no argument is given. If argument "save" is"
    echo "present, current settings are stored as factory defaults."
    echo
    exit 0
fi 

if [ "$#" -eq "0" ]; then
	/etc/init.d/runtime stop
	/etc/config-tools/settings_backup restore "$DEFAULT_SETTINGS_DIR/$DEFAULT_SETTINGS_FILENAME"
	cp -p $DEFAULT_SETTINGS_DIR/shadow.default /etc/shadow
	cp -p $DEFAULT_SETTINGS_DIR/group.default /etc/group
	cp -p $DEFAULT_SETTINGS_DIR/passwd.default /etc/passwd 
	rm -rf /home/codesys/*
	rm -rf /home/user/bacnet/*
	# Need not to start runtime again, system will reboot
else
	case $1 in
	save)
		# check if default settings file is existing and if not - create it with actual settings
		if [ ! -f "$DEFAULT_SETTINGS_DIR/$DEFAULT_SETTINGS_FILENAME.md5" ]; then
			echo "Create default settings file..."
			mkdir -p ${DEFAULT_SETTINGS_DIR}
			/etc/config-tools/settings_backup save ${DEFAULT_SETTINGS_DIR}/${DEFAULT_SETTINGS_FILENAME} &> /dev/null
			chown root:shadow "${DEFAULT_SETTINGS_DIR}/${DEFAULT_SETTINGS_FILENAME}"
			cp -p /etc/shadow $DEFAULT_SETTINGS_DIR/shadow.default
			cp -p /etc/group $DEFAULT_SETTINGS_DIR/group.default
			cp -p /etc/passwd $DEFAULT_SETTINGS_DIR/passwd.default
			sync
			md5sum "$DEFAULT_SETTINGS_DIR/$DEFAULT_SETTINGS_FILENAME" > "$DEFAULT_SETTINGS_DIR/$DEFAULT_SETTINGS_FILENAME.md5"
			sync
		fi
		;;
	*)
		SetLastError "Unknown argument \"$1\""
		;;
	esac
fi
exit 0

