#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018-2022 WAGO GmbH & Co. KG

#
# Firewall: dns demon events handler
#

enabled=$(/etc/config-tools/firewall firewall --is-enabled)
[ "enabled" != "$enabled" ] && exit 0


start()
{
	local NET_PARAMS=""

    if [[ -n ${NETCONF_BRIDGE_CONFIG+x} && -n ${NETCONF_IP_CONFIG+x} && -n ${NETCONF_INTERFACE_CONFIG+x} ]]; then
        NET_PARAMS="--bridge-config $NETCONF_BRIDGE_CONFIG --ip-config $NETCONF_IP_CONFIG --interface-config $NETCONF_INTERFACE_CONFIG"
    fi
		
    running=$(/etc/config-tools/get_dns_service_config -g dns-state "$NET_PARAMS")

    if [ "enabled" == "$running" ] ; then
        action="up"
    else
        action="down"
    fi

    /etc/config-tools/firewall dns --apply ${action} >/dev/null 2>&1
}

stop()
{
    /etc/config-tools/firewall dns --apply down >/dev/null 2>&1
}

case "$1" in
    start|config)
        start;;
    stop)
        stop;;
    *)
        ;;
esac
