# -*-makefile-*-
# $Id: template-make 8509 2008-06-12 12:45:40Z mkl $
#
# Copyright (C) 2012 by WAGO
#
# See CREDITS for details about who has contributed to this project.
#
# For further information about the PTXdist project and license conditions
# see the README file.
#

#
# We provide this package
#
PACKAGES-$(PTXCONF_DAL) += dal

#
# Paths and names
#
DAL_VERSION	:= 0.0.1
DAL		:= dal
DAL_URL		:= file://$(PTXDIST_WORKSPACE)/wago_intern/$(DAL)
DAL_DIR		:= $(BUILDDIR)/$(DAL)-$(DAL_VERSION)
DAL_UTEST_DIR := $(DAL_DIR)/host-utests-autogenerated
DAL_SRC     := $(PTXDIST_WORKSPACE)/wago_intern/dal

DAL_PACKAGE_NAME := $(DAL)_$(DAL_VERSION)_$(PTXDIST_IPKG_ARCH_STRING)
DAL_PLATFORMCONFIGPACKAGEDIR := $(PTXDIST_PLATFORMCONFIGDIR)/packages

# ----------------------------------------------------------------------------
# Get
# ----------------------------------------------------------------------------
$(STATEDIR)/dal.get:
	@$(call targetinfo)
	@$(call touch)

# ----------------------------------------------------------------------------
# Extract
# ----------------------------------------------------------------------------

$(STATEDIR)/dal.extract:
	@$(call targetinfo)
	@mkdir -p $(DAL_DIR)
ifndef PTXCONF_WAGO_TOOLS_BUILD_VERSION_BINARIES
 	# WAGO_TOOLS_BUILD_VERSION_TRUNK | WAGO_TOOLS_BUILD_VERSION_RELEASE
	rsync -a --exclude=".*" --exclude="dal_tests" --exclude=".doc" --exclude=project/output/ --exclude="*.d" --exclude="*.o" --exclude="libdal.a" $(DAL_SRC)/* $(DAL_DIR)
ifdef PTXCONF_WAGO_TOOLS_BUILD_VERSION_TRUNK
	rsync -a --exclude=".*" --exclude="dal_tests" --exclude=".doc" --exclude=project/output/ --exclude="*.d" --exclude="*.o" --exclude="libdal.a" $(DAL_SRC)/* $(DAL_UTEST_DIR)
endif
endif
	@$(call touch)

# ----------------------------------------------------------------------------
# Prepare
# ----------------------------------------------------------------------------

DAL_PATH := PATH=$(CROSS_PATH)
DAL_ENV:= $(CROSS_ENV) 

ifdef PTXCONF_WAGO_TOOLS_BUILD_VERSION_RELEASE
	DAL_ENV+=CFLAGS="$(CROSS_CFLAGS) -DNDEBUG"
endif

# extra vars for host unit tests
DAL_UTEST_PATH	:= $(HOST_PATH)
DAL_UTEST_ENV := $(HOST_ENV) CPPUTEST_HOME=$(PTXCONF_SYSROOT_HOST)/usr/local _SYSROOT_HOST=$(PTXCONF_SYSROOT_HOST)

$(STATEDIR)/dal.prepare:
	@$(call targetinfo)
	@$(call touch)

# ----------------------------------------------------------------------------
# Compile
# ----------------------------------------------------------------------------
SYSROOT_TARGET = $(PTXDIST_PLATFORMDIR)/sysroot-target

$(STATEDIR)/dal.compile:
	@$(call targetinfo)
ifdef PTXCONF_WAGO_TOOLS_BUILD_VERSION_TRUNK 
   	# build a host version of DAL to run the host-side unit tests on (build lib example first as it is needed for the tests) 
	cd $(DAL_UTEST_DIR)/project && SYSROOT_TARGET=$(SYSROOT_TARGET) PATH=$(DAL_UTEST_PATH) $(DAL_UTEST_ENV) $(MAKE) -f Makefile examples
	cd $(DAL_UTEST_DIR) && SYSROOT_TARGET=$(SYSROOT_TARGET) PATH=$(DAL_UTEST_PATH) $(DAL_UTEST_ENV) $(MAKE) -f tests/Makefile 
endif
ifndef PTXCONF_WAGO_TOOLS_BUILD_VERSION_BINARIES
 	# WAGO_TOOLS_BUILD_VERSION_TRUNK | WAGO_TOOLS_BUILD_VERSION_RELEASE	
	cd $(DAL_DIR)/project && \
		SYSROOT_TARGET=$(SYSROOT_TARGET) \
		CROSS_COMPILE=$(COMPILER_PREFIX) \
		$(DAL_ENV)\
		$(DAL_PATH) \
		$(MAKE) -f Makefile  $(PARALLELMFLAGS)
endif
	@$(call touch)

# ----------------------------------------------------------------------------
# Install
# ----------------------------------------------------------------------------

$(STATEDIR)/dal.install:
	@$(call targetinfo)
	mkdir -p $(PTXCONF_SYSROOT_TARGET)/usr/include/dal/events
ifndef PTXCONF_WAGO_TOOLS_BUILD_VERSION_BINARIES
	# WAGO_TOOLS_BUILD_VERSION_TRUNK | WAGO_TOOLS_BUILD_VERSION_RELEASE	
	# export public interfaces
	cp $(DAL_DIR)/include/adi_application_interface.h  $(PTXCONF_SYSROOT_TARGET)/usr/include/dal/
	cp $(DAL_DIR)/include/dal_limits.h  $(PTXCONF_SYSROOT_TARGET)/usr/include/dal/
	cp $(DAL_DIR)/include/dal_caps.h  $(PTXCONF_SYSROOT_TARGET)/usr/include/dal/
	cp $(DAL_DIR)/include/dal_types.h  $(PTXCONF_SYSROOT_TARGET)/usr/include/dal/
	cp $(DAL_DIR)/include/sdi_stack_interface.h  $(PTXCONF_SYSROOT_TARGET)/usr/include/dal/
	cp $(DAL_DIR)/include/events/events.h $(PTXCONF_SYSROOT_TARGET)/usr/include/dal/events/
	cp $(DAL_DIR)/project/libdal.a $(PTXCONF_SYSROOT_TARGET)/usr/lib
ifdef PTXCONF_WAGO_TOOLS_BUILD_VERSION_RELEASE
	#Backup header files as archive for later use in configs/@platform@/packages
	cd $(PTXCONF_SYSROOT_TARGET) && \
	tar -czvf $(DAL_PACKAGE_NAME).tgz \
	usr/include/dal/adi_application_interface.h \
	usr/include/dal/dal_limits.h  \
	usr/include/dal/dal_caps.h   \
	usr/include/dal/dal_types.h  \
	usr/include/dal/sdi_stack_interface.h \
	usr/include/dal/events/events.h  \
	usr/lib/libdal.a  && \
	mv $(DAL_PACKAGE_NAME).tgz $(DAL_PLATFORMCONFIGPACKAGEDIR)
endif
else
	#PTXCONF_WAGO_TOOLS_BUILD_VERSION_BINARIES - Install header files from archive
	cd $(DAL_PLATFORMCONFIGPACKAGEDIR) && \
	tar -xzvf $(DAL_PACKAGE_NAME).tgz -C $(PTXCONF_SYSROOT_TARGET)
endif
	@$(call touch)

# ----------------------------------------------------------------------------
# Target-Install
# ----------------------------------------------------------------------------

$(STATEDIR)/dal.targetinstall:
	@$(call targetinfo)
	@$(call touch)

# ----------------------------------------------------------------------------
# Clean
# ----------------------------------------------------------------------------

$(STATEDIR)/dal.clean:
	rm -rf $(STATEDIR)/dal*
	rm -rf $(PKGDIR)/dal*
	rm -rf $(DAL_DIR)
	rm -rf $(PTXCONF_SYSROOT_TARGET)/usr/include/dal
	rm -rf $(PTXCONF_SYSROOT_TARGET)/usr/lib/libdal.a

